[FIX] Dependencie of connector_elasticsearch
shopinvader/odoo-shopinvader pull request #1017
Opened 2021-07-11 23:37 UTC by mileo

2021-07-12 07:16 UTC, simahawk requested changes

2021-07-12 07:16 UTC, simahawk commented on shopinvader_demo_app/__manifest__.py
> +        "connector_elasticsearch",
IDT this is required since `shopinvader_elasticsearch` depends on it

2021-07-12 07:16 UTC, simahawk commented on shopinvader_demo_app/__manifest__.py
> +        "connector_elasticsearch",
BTW the base branch of this PR is 14 but the module version is 12 :thinking:

2021-07-13 17:53 UTC, mileo commented
@simahawk thanks for your review, but i need to create this fix to bypass the error above:

```
Attaching to kmee-shop-invader_odoo_1
[36modoo_1        |[0m Starting with UID : 1000
[36modoo_1        |[0m Running without demo data
[36modoo_1        |[0m /src/*.egg-info is missing, probably because the directory is a volume.
[36modoo_1        |[0m Running pip install -e /odoo to restore *.egg-info
[36modoo_1        |[0m Obtaining file:///odoo
[36modoo_1        |[0m Installing collected packages: analogica
[36modoo_1        |[0m   Running setup.py develop for analogica
[36modoo_1        |[0m Successfully installed analogica-12.0.0.0.0
[36modoo_1        |[0m WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[36modoo_1        |[0m 2021/07/13 17:33:50 Waiting for: tcp://db:5432
[36modoo_1        |[0m 2021/07/13 17:33:50 Connected to tcp://db:5432
[36modoo_1        |[0m Traceback (most recent call last):
[36modoo_1        |[0m   File "/usr/local/bin/marabunta", line 8, in <module>
[36modoo_1        |[0m     sys.exit(main())
[36modoo_1        |[0m   File "/usr/local/lib/python3.7/dist-packages/marabunta/core.py", line 154, in main
[36modoo_1        |[0m     migrate(config)
[36modoo_1        |[0m   File "/usr/local/lib/python3.7/dist-packages/marabunta/core.py", line 143, in migrate
[36modoo_1        |[0m     runner.perform()
[36modoo_1        |[0m   File "/usr/local/lib/python3.7/dist-packages/marabunta/runner.py", line 59, in perform
[36modoo_1        |[0m     .format(u','.join(v.number for v in unfinished))
[36modoo_1        |[0m marabunta.exception.MigrationError: Upgrade of version setup has been attempted and failed. You may want to restore the backup or to run again the migration with the MARABUNTA_FORCE_VERSION environment variable or to fix it manually (in that case, you will have to update the  'marabunta_version' table yourself.
[36modoo_1        |[0m Starting with UID : 1000
[36modoo_1        |[0m Running without demo data
[36modoo_1        |[0m 2021/07/13 17:38:35 Waiting for: tcp://db:5432
[36modoo_1        |[0m 2021/07/13 17:38:35 Connected to tcp://db:5432
[36modoo_1        |[0m [1m|> migration: processing version setup[0m
[36modoo_1        |[0m [1m|> version setup: start[0m
[36modoo_1        |[0m [1m|> version setup: execute base pre-operations[0m
[36modoo_1        |[0m [1m|> version setup: echo 'pre-operation'[0m
[36modoo_1        |[0m pre-operation
[36modoo_1        |[0m [1m|> version setup: execute full pre-operations[0m
[36modoo_1        |[0m [1m|> version setup: installation / upgrade of addons[0m
[36modoo_1        |[0m [1m|> version setup: odoo --workers=0 --stop-after-init --no-xmlrpc -i remove_odoo_enterprise,mail_debrand,shopinvader_demo_app,base_technical_features,web_responsive,auth_admin_passkey,disable_odoo_online[0m
[36modoo_1        |[0m 2021-07-13 17:38:40,400 71 [1;32m[1;49mINFO[0m ? odoo: Odoo version 12.0 
[36modoo_1        |[0m 2021-07-13 17:38:40,401 71 [1;32m[1;49mINFO[0m ? odoo: Using configuration file at /etc/odoo.cfg 
[36modoo_1        |[0m 2021-07-13 17:38:40,401 71 [1;32m[1;49mINFO[0m ? odoo: addons paths: ['/data/odoo/addons/12.0', '/odoo/links', '/odoo/local-src', '/odoo/src/odoo/addons', '/odoo/src/addons', '/odoo/external-src/account-payment', '/odoo/external-src/account-invoicing', '/odoo/external-src/bank-payment', '/odoo/external-src/currency', '/odoo/external-src/server-tools', '/odoo/external-src/server-env', '/odoo/external-src/server-ux', '/odoo/external-src/stock-logistics-workflow', '/odoo/external-src/stock-logistics-warehouse', '/odoo/external-src/stock-logistics-reporting', '/odoo/external-src/wms', '/odoo/external-src/sale-workflow', '/odoo/external-src/purchase-workflow', '/odoo/external-src/partner-contact', '/odoo/external-src/delivery-carrier', '/odoo/external-src/account-financial-tools', '/odoo/external-src/social', '/odoo/external-src/product-attribute', '/odoo/external-src/reporting-engine', '/odoo/external-src/queue', '/odoo/external-src/contract', '/odoo/external-src/mis-builder', '/odoo/external-src/crm', '/odoo/external-src/account-financial-reporting', '/odoo/external-src/account-invoice-reporting', '/odoo/external-src/credit-control', '/odoo/external-src/server-brand', '/odoo/external-src/helpdesk', '/odoo/external-src/manufacture', '/odoo/external-src/storage', '/odoo/external-src/web', '/odoo/external-src/geospatial', '/odoo/external-src/rest-framework', '/odoo/external-src/search-engine', '/odoo/external-src/stock-logistics-barcode', '/odoo/external-src/report-print-send', '/odoo/external-src/connector', '/odoo/external-src/data-protection', '/odoo/external-src/donation', '/odoo/external-src/sale-reporting', '/odoo/external-src/margin-analysis', '/odoo/external-src/product-pack', '/odoo/external-src/purchase-reporting', '/odoo/external-src/odoo-shopinvader', '/odoo/external-src/odoo-cloud-platform', '/odoo/external-src/l10n-brazil', '/odoo/external-src/commission', '/odoo/external-src/odoo-zone', '/odoo/external-src/account-closing', '/odoo/external-src/account-reconcile', '/odoo/external-src/server-backend', '/odoo/external-src/server-auth', '/odoo/external-src/e-commerce', '/odoo/external-src/product-variant', '/odoo/external-src/odoo-misc', '/odoo/external-src/odoo-shopinvader-payment'] 
[36modoo_1        |[0m 2021-07-13 17:38:40,401 71 [1;32m[1;49mINFO[0m ? odoo: database: odoo@db:5432 
[36modoo_1        |[0m 2021-07-13 17:38:40,474 71 [1;32m[1;49mINFO[0m ? odoo.addons.server_environment.serv_config: not using server_environment_files for configuration, no directory found 
[36modoo_1        |[0m 2021-07-13 17:38:40,772 71 [1;32m[1;49mINFO[0m ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
[36modoo_1        |[0m 2021-07-13 17:38:41,119 71 [1;33m[1;49mWARNING[0m ? odoo.modules.registry: The option --unaccent was given but no unaccent() function was found in database. 
[36modoo_1        |[0m 2021-07-13 17:38:41,126 71 [1;32m[1;49mINFO[0m ? odoo.modules.loading: init db 
[36modoo_1        |[0m 2021-07-13 17:38:55,719 71 [1;32m[1;49mINFO[0m odoo odoo.modules.loading: loading 1 modules... 
[36modoo_1        |[0m 2021-07-13 17:38:55,871 71 [1;32m[1;49mINFO[0m odoo odoo.modules.registry: module base: creating or updating database tables 
[36modoo_1        |[0m 2021-07-13 17:38:56,203 71 [1;32m[1;49mINFO[0m odoo odoo.models: Computing parent_path for table ir_ui_menu... 
[36modoo_1        |[0m 2021-07-13 17:38:57,359 71 [1;32m[1;49mINFO[0m odoo odoo.models: Computing parent_path for table res_partner_category... 
[36modoo_1        |[0m 2021-07-13 17:38:57,953 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.model.fields.relation_field_id 
[36modoo_1        |[0m 2021-07-13 17:38:57,959 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.model.fields.related_field_id 
[36modoo_1        |[0m 2021-07-13 17:38:58,393 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.attachment.res_name 
[36modoo_1        |[0m 2021-07-13 17:38:58,395 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.attachment.res_model_name 
[36modoo_1        |[0m 2021-07-13 17:38:58,511 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.rule.global 
[36modoo_1        |[0m 2021-07-13 17:38:58,687 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.module.module.menus_by_module 
[36modoo_1        |[0m 2021-07-13 17:38:58,697 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.module.module.reports_by_module 
[36modoo_1        |[0m 2021-07-13 17:38:58,709 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of ir.module.module.views_by_module 
[36modoo_1        |[0m 2021-07-13 17:38:58,948 71 [1;32m[1;49mINFO[0m odoo odoo.models: Storing computed values of res.partner.display_name 
[36modoo_1        |[0m 2021-07-13 [...]

2021-07-13 18:12 UTC, mileo commented
my bad, running without demo :@

2021-07-13 18:12 UTC, closed without merging