[IMP+FIX][14.0] shopinvader_import_image
shopinvader/odoo-shopinvader pull request #1068
Opened 2021-08-11 14:09 UTC by ivantodorovich

Description in commits

2021-08-11 14:21 UTC, simahawk requested changes

2021-08-11 14:21 UTC, simahawk commented on shopinvader_import_image/models/import_image.py
> +            headers = self.csv_header.split(self.csv_delimiter)
to be changed as per our chat to provide real mapping of fields :wink:

2021-08-11 14:58 UTC, ivantodorovich commented
Ready. Changed with a real mapping and dictreader

2021-08-12 06:10 UTC, simahawk reviewed
can you post a screenshot?

2021-08-12 06:10 UTC, simahawk commented on shopinvader_import_image/models/import_image.py
> +                line = {key: row.get(column) for key, column in mapping.items()}
do not use get and let it raise a KeyError, catch that exception and raise a UserError "CSV schema imcompatible" or something similar

2021-08-12 06:10 UTC, simahawk commented on shopinvader_import_image/views/import_product_image_view.xml
> +                        <group name="output" string="Import">
```suggestion
                        <group name="destination" string="Destination">
```

2021-08-12 11:52 UTC, ivantodorovich commented
Suggestions applied and posted a screenshot in the PR description :)

2021-08-12 12:41 UTC, simahawk approved these changes
waaaay better tnx!

2021-08-12 12:41 UTC, simahawk commented on shopinvader_import_image/models/import_image.py
> +                if line:
this IF seems useless

2021-08-12 13:15 UTC, ivantodorovich commented on shopinvader_import_image/models/import_image.py
> +                if line:
indeed!

2021-08-18 12:05 UTC, sebalix approved these changes

2021-08-18 12:08 UTC, simahawk commented
/ocabot merge minor

2021-08-18 12:31 UTC, merged