[13.0][MIG] shopinvader_product_attribute_set
shopinvader/odoo-shopinvader pull request #1096
Opened 2021-09-09 08:15 UTC by HviorForgeFlow

Standard migration:

- [x] Backport from 14.0
- [ ] Fix Native field export
- [ ] Add test for Native field

CC @ForgeFlow

2021-10-14 11:50 UTC, HviorForgeFlow commented
Any suggestions about how to fix this? https://github.com/shopinvader/odoo-shopinvader/pull/1096/commits/760c1b74a1f8003e1d90f369705b98631dc889c9

Thanks!

2021-10-14 12:49 UTC, MiquelRForgeFlow commented on shopinvader_product_attribute_set/models/shopinvader_variant.py
> +            # float_round(self[attr.name], precision_digits=attr.field_id.get_digits())
```suggestion
            float_round(self[attr.name], precision_digits=self.env[attr.field_id.model]._fields[attr.field_id.name].get_digits(self.env)[1])
```

2022-03-17 16:15 UTC, HviorForgeFlow commented
@rousseldenis @sebastienbeau @Cedric-Pigeon can we move it forward? Thanks!

2022-03-25 07:49 UTC, rousseldenis approved these changes
LGTM

2022-06-15 08:28 UTC, acsonefho requested changes

2022-06-15 08:28 UTC, acsonefho commented on shopinvader_product_attribute_set/models/product_filter.py
> +        ondelete="cascade",
`ondelete="cascade"`? Why?

2022-06-15 08:34 UTC, acsonefho commented on shopinvader_product_attribute_set/models/product_filter.py
> +        ondelete="cascade",
Ok that's correct.

2022-06-15 08:34 UTC, acsonefho approved these changes

2022-06-15 08:38 UTC, acsonefho requested changes
`ondelete="cascade"` doesn't exist in v13.0 for `Selection` fields.

2022-06-15 08:58 UTC, HviorForgeFlow commented
> `ondelete="cascade"` doesn't exist in v13.0 for `Selection` fields.

ondelete removed from the selection field

2022-06-15 10:10 UTC, PierrickBrun approved these changes

2022-06-15 10:23 UTC, MiquelRForgeFlow approved these changes

2022-09-13 07:23 UTC, HviorForgeFlow commented
@rousseldenis @PierrickBrun can this be merged? Used in production for a while

2022-09-13 07:43 UTC, PierrickBrun commented
/ocabot merge patch

2022-09-13 08:04 UTC, merged