[13.0][MIG] shopinvader_sale_communication
shopinvader/odoo-shopinvader pull request #1101
Opened 2021-09-13 14:41 UTC by JordiMForgeFlow

Standard migration to 13.0

2021-09-14 07:48 UTC, JordiMForgeFlow commented
Hi @simahawk @sebastienbeau @rousseldenis ,

Could I get some reviews here? :)

2021-10-05 17:27 UTC, sebastienbeau commented on shopinvader_sale_communication/services/abstract_sale.py
> +                else False,
```suggestion
                else None,
```
False is for Boolean ;)

2021-10-05 17:27 UTC, sebastienbeau requested changes
LGTM, small requested change

2021-10-05 17:34 UTC, JordiMForgeFlow commented on shopinvader_sale_communication/services/abstract_sale.py
> +                else False,
My bad! Thanks for spotting it :))

2021-10-12 11:21 UTC, lmignon approved these changes
LGTM (Code review only)
I'm wondering why you don't use the chatter to manage communications to the customer. It could be usefull to have a generic service to get access to the customer's messages into odoo (messages on models linked to the customer). This mechanism could be easy to put in place by using the [new way to get the logged partner id](https://github.com/OCA/rest-framework/pull/204) and [defining the right record rules](https://github.com/OCA/rest-framework/blob/14.0/base_rest/models/ir_rule.py#L7).

2021-11-08 19:49 UTC, ivantodorovich approved these changes

2024-03-24 12:15 UTC, closed without merging