[ADD] shopinvader_product_manufactured_for
shopinvader/odoo-shopinvader pull request #1164
Opened 2021-11-08 03:33 UTC by kv1612

2021-11-08 14:38 UTC, mmequignon approved these changes

2021-11-09 10:37 UTC, simahawk requested changes

2021-11-09 10:37 UTC, simahawk commented on shopinvader_product_manufactured_for/readme/DESCRIPTION.rst
> +one implementing the export to Shopinvader.
```suggestion
Glue module between `sale_product_manufactured_for` and Shopinvader.
```

2021-11-09 12:39 UTC, kv1612 commented
Hi @simahawk, Thank for your review. I have just updated DESCRIPTION.rst.

2021-11-10 13:29 UTC, simahawk approved these changes

2021-12-01 07:43 UTC, simahawk commented
@kv1612 pls rebase and check pre-commit

2021-12-01 14:00 UTC, kv1612 commented
Hi @simahawk, this PR has been updated.

2021-12-02 06:24 UTC, simahawk commented
/ocabot merge nobump

2021-12-02 07:05 UTC, merged