[ADD] Add shopinvader stock + shopinvader algolia stock
shopinvader/odoo-shopinvader pull request #126
Opened 2018-05-25 07:50 UTC by acsonefho

This MR depends on the MR akretion/connector-search-engine/pull/24
Still a strange behaviour into Unit test:
If you create a new Unit test (into shopinvader_stock module) file without using the the test.se.backend Model, you will have an error if you try to create a se.backend. Due to this test.se.backend model.
Odoo try to load it but this one is not into the registry and not into the Database... So Boom!
If someone can check and maybe fix what I miss, that'll be great!

2018-05-25 16:34 UTC, lmignon commented on shopinvader_algolia_stock/__manifest__.py
> +        Connector search engine for Algolia Stock""",
@acsonefho The description should be more meaningful.  'This module adds the stock levele of your products to the informations exported to Aalgolia'

2018-05-25 16:35 UTC, lmignon commented on shopinvader_stock/__manifest__.py
> +        Connector search engine for Stock""",
@acsonefho same comment as above

2018-05-25 16:41 UTC, lmignon commented on shopinvader_stock/models/stock_move.py
> +    def _product_stock_update_all(self):
@acsonefho These following 3 methods should be placed into product.product...

2018-06-18 12:39 UTC, Cedric-Pigeon commented on shopinvader_algolia_product_stock/__manifest__.py
> +    },
'pre_init_hook': 'rename_module' is missing

2018-06-18 12:49 UTC, lmignon commented on shopinvader_product_stock/__manifest__.py
> +    'pre_init_hook': 'rename_module',
This name is not conform to OCA guidelines

2018-08-06 20:44 UTC, rousseldenis requested changes
Some remarks (one blocking)

2018-08-06 20:44 UTC, rousseldenis commented on shopinvader_product_stock/models/product_product.py
> +        shopinvader_variants = products.shopinvader_bind_ids.filtered(
@acsonefho products can be multi, so it raises error. Use mapped on shopinvader_bind_ids

2018-08-06 20:44 UTC, rousseldenis commented on shopinvader_product_stock/models/product_product.py
> +        shopinvader_variants = self._get_shopinvader_variants_from_product(
@acsonefho Maybe creating a 'shopinvader_variants' computed field on product.product ?

2018-08-06 20:44 UTC, rousseldenis commented on shopinvader_product_stock/models/se_backend.py
> +    product_stock_field_id = fields.Many2one(
Is this working without being administrator (in view)?

2018-08-14 12:52 UTC, sebastienbeau commented
I have done a PR that includ this one with a refactoring in order to:
- use the existing exporter for defining the key in the export
- support specific warehouse for stock level (also support multi warehouse)
- export in algolia only if stock level have change, as export is now done in two step (first compute json independently, then export it in batch)
The new PR is here : https://github.com/akretion/odoo-shopinvader/pull/182

2018-08-20 08:44 UTC, sebastienbeau commented
This have been merged here with a refactoring : https://github.com/akretion/odoo-shopinvader/pull/182

2018-08-20 08:44 UTC, closed without merging