[ADD] shopinvader_assortment : wizard to remove product from backend
shopinvader/odoo-shopinvader pull request #1272
Opened 2022-04-05 12:00 UTC by xavier-bouquiaux

the goal is to add a wizard to facilitate the end-user experience
if he wants to exclude x product from y backend he has to open every ir_filter and exclude those
with this wizard he can do it in one step
just pay attention to action_type include
as explained in the help, it can't be used to add a product to a filter
just to enable again a product that has been removed in the past

2022-04-08 14:14 UTC, rousseldenis requested changes

2022-04-08 14:14 UTC, rousseldenis commented on shopinvader_assortment/wizards/wizard_online_availability.py
> +    _name = "wizard.online_availability"
```suggestion
    _name = "wizard.shopinvader_backend_availability"
```

2022-04-08 14:14 UTC, rousseldenis commented on shopinvader_assortment/wizards/wizard_online_availability.py
> +        help="If checked, the product(s) will be excluded from all backend",
```suggestion
        help="If checked, the product(s) will be excluded from all backends",
```

2022-04-08 14:14 UTC, rousseldenis commented on shopinvader_assortment/wizards/wizard_online_availability.py
> +                    "blacklist_product_ids": [(6, 0, new_blacklist)],
As the change you propose is to populate blacklist (you don't change whitelist), IMHO the whole changes must explain it.

e.g.: The name of the wizard, an explanation text in wizard view, 'Online availability'  is too generic, ...

2022-04-22 09:40 UTC, rousseldenis commented
@xavier-bouquiaux

2022-04-22 12:05 UTC, acsonefho requested changes

2022-04-22 12:05 UTC, acsonefho commented on shopinvader_assortment/tests/test_wizard_online_availability.py
> +            self.assertIn(
That should be outside of the `with` section to work properly.

2022-04-22 12:05 UTC, acsonefho commented on shopinvader_assortment/tests/test_wizard_online_availability.py
> +        for backend in backends:
As this part is used and duplicated many times, you can extract it.

2022-04-22 12:05 UTC, acsonefho commented on shopinvader_assortment/wizards/wizard_online_availability.py
> +        if not self.all_backend and len(self.backend_ids) == 0:
Please add `self.ensure_one()`

2022-04-25 05:18 UTC, xavier-bouquiaux commented
Thanks for the review but the client changed the scope of this . <br/>
We decided to make it an custom module <br/>
As we won't work on this PR anymore -> i'll close it <br/>

2022-04-25 05:18 UTC, closed without merging