[14.0] [FIX] shopinvader: don't create cart on search
shopinvader/odoo-shopinvader pull request #1281
Opened 2022-04-25 17:43 UTC by ivantodorovich

`search` shouldn't create a cart if missing.

This covers the case where a `cart_id` is present in the session, but it references a cart that's no longer a valid cart for our service.

2022-04-26 06:24 UTC, jcoux approved these changes

2022-04-26 07:23 UTC, simahawk approved these changes
seems legit

2022-05-12 15:47 UTC, simahawk commented
Looking at this twice, while I think it's correct, we might be breaking existing frontend implementations.
@sebastienbeau @rousseldenis @lmignon do you remember if this (getting a default cart on search) was done for a specific reason?

2022-05-13 06:12 UTC, lmignon requested changes
AFAIK, the cart service is expected to **always** return the current cart in this implementation. (when used with locomotive). In the [new implementation](https://github.com/acsone/odoo-shopinvader/tree/10.0-backport-with-new-cart-service/sale_cart_rest_api) (developed on  10.0 and designed to work with the js cart library) a cart is only created if no cart exists and transactions must be applied. This new implementation will be migrated in the next few months.

2022-05-13 06:13 UTC, lmignon commented
ping @Cedric-Pigeon

2022-10-20 11:23 UTC, ivantodorovich commented
Ok to merge then? 👀

2023-06-14 19:07 UTC, sebastienbeau approved these changes
if there is not cart the search service should not create any cart.
I think the bug have been introduced when the _get method have been change.
 if the cart_id session is invalid it's indeed better to return nothing and to not create a cart.
We only need to create a cart when we add an item (or set other element on the cart)

2023-06-14 19:07 UTC, sebastienbeau commented
I think @lmignon you can remove your blocking review, it should not raise any issue

2023-06-15 06:36 UTC, lmignon approved these changes

2023-06-15 06:37 UTC, lmignon commented
/ocabot merge patch

2023-06-15 06:59 UTC, merged