14.0 add shopinvader customer delivery
shopinvader/odoo-shopinvader pull request #1313
Opened 2022-08-01 15:13 UTC by mourad-ehm

2022-08-01 15:13 UTC, mourad-ehm commented
@hparfr

2022-08-02 15:30 UTC, hparfr requested changes

2022-08-02 15:30 UTC, hparfr commented on shopinvader_customer_delivery/__manifest__.py
> +    "depends": ["account", "shopinvader"],
account?

2022-08-02 15:30 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +    _inherit = ["base.shopinvader.service", "abstract.shopinvader.download"]
why download ?

2022-08-02 15:30 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +        print([("sale_id", "in", sales.ids)] + self._get_allowed_stock_move_domain())
print ?!

2022-09-13 14:41 UTC, hparfr commented on shopinvader_customer_delivery/__manifest__.py
> +    "depends": ["account", "shopinvader"],
still this one

2022-09-13 14:43 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +        if states:
useless condition

2022-09-13 14:44 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +    def _add_product_info(self, stok_move):
typo

2022-09-13 14:44 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +        sale_order = stok_move.product_id
wrong  variable name

2022-09-13 14:44 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +    def _get_parser_sale_order(self):
wrong variable name

2022-10-18 08:11 UTC, hparfr requested changes

2022-10-18 08:11 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +        sale_order = stok_move.product_id
@mourad-ehm please fix !

2022-10-18 08:14 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +    def _add_product_info(self, stok_move):
```suggestion
    def _add_product_info(self, stock_move):
```

2022-10-18 08:14 UTC, hparfr commented on shopinvader_customer_delivery/services/stock_move.py
> +        return values
```suggestion
        if not product:
            return {}
        parser = self._get_parser_product()
        values = product.jsonify(parser, one=True)
        return values
```

2022-10-19 11:09 UTC, mourad-ehm commented on shopinvader_customer_delivery/services/stock_move.py
> +        sale_order = stok_move.product_id
```suggestion
        sale_order = stock_move.product_id
```

2022-10-19 11:10 UTC, mourad-ehm commented on shopinvader_customer_delivery/services/stock_move.py
> +    def _get_parser_sale_order(self):
Which ?

2022-10-19 11:12 UTC, mourad-ehm commented on shopinvader_customer_delivery/__manifest__.py
> +    "depends": ["account", "shopinvader"],
```suggestion
    "depends": ["stock", "shopinvader"],
```

2022-10-19 11:13 UTC, mourad-ehm commented on shopinvader_customer_delivery/__manifest__.py
> +    "depends": ["account", "shopinvader"],
```suggestion
    "depends": ["stock", "shopinvader"],
```

2022-10-19 11:16 UTC, mourad-ehm commented on shopinvader_customer_delivery/services/stock_move.py
> +            domain.append(("state", "in", states))
```suggestion
```

2022-10-19 11:16 UTC, mourad-ehm commented on shopinvader_customer_delivery/services/stock_move.py
> +        if states:
```suggestion
        domain.append(("state", "in", states))
```

2024-08-18 12:19 UTC, closed without merging