[13.0][IMP]shopinvader: one active partner per email and backend
shopinvader/odoo-shopinvader pull request #1330
Opened 2022-10-27 10:12 UTC by GuillemCForgeFlow

Removed _sql_constraints checking that there were not two partners having the same email within the same backend. Changed it for an api.constrains that will only check it for active users.
cc https://github.com/ForgeFlow

2022-10-27 13:36 UTC, JordiMForgeFlow approved these changes

2022-10-27 13:49 UTC, simahawk requested changes

2022-10-27 13:49 UTC, simahawk commented on shopinvader/models/shopinvader_partner.py
> +                active_partners = self.env["shopinvader.partner"].search(
```suggestion
                active_partners = self.search_count(
```

2022-10-27 13:49 UTC, simahawk commented on shopinvader/models/shopinvader_partner.py
> +                active_partners = self.env["shopinvader.partner"].search(
Although, a read_group w/ 1 query only would be probably be better ;)

2022-10-27 15:31 UTC, GuillemCForgeFlow commented on shopinvader/models/shopinvader_partner.py
> +                active_partners = self.env["shopinvader.partner"].search(
Great, I have applied the changes.
Thank you for the feedback :smile:

2022-10-28 06:34 UTC, simahawk approved these changes

2024-09-08 12:18 UTC, closed without merging