[16.0][MIG] shopinvader_search_engine_product_stock: Migration to 16.0
shopinvader/odoo-shopinvader pull request #1431
Opened 2023-10-19 16:08 UTC by qgroulard

* [ ]  depends on https://github.com/OCA/product-attribute/pull/1339

2023-10-25 13:41 UTC, lmignon requested changes
@qgroulard Good job. Some little comments...

2023-10-25 13:41 UTC, lmignon commented on shopinvader_search_engine_product_stock/models/product_product.py
> +    stock_data = Serialized(compute="_compute_stock_data")
```suggestion
    stock_data = fields.Json(compute="_compute_stock_data")
```
same functionality for computed fields but without additional dependency on base_sparse_field.

2023-10-25 13:41 UTC, lmignon commented on shopinvader_search_engine_product_stock/models/product_product.py
> +    @api.depends_context("index")
@qgroulard AFAIK `index` is not into the context only `index_id`  see See https://github.com/OCA/search-engine/blob/16.0/connector_search_engine/models/se_binding.py#L137

2023-10-25 13:41 UTC, lmignon commented on shopinvader_search_engine_product_stock/models/se_index.py
> -# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Can you keep the initial authors...

2023-10-25 13:41 UTC, lmignon commented on shopinvader_search_engine_product_stock/models/se_index.py
> +    _inherit = "se.index"
A nice to have could be to have the stock level configurable on the backend if some indexes are configured for the product model. By default the value on the backend should be used except if a specific one is defined on the index.  It's to avoid to have to define the same value multiple times.

2023-10-26 13:31 UTC, qgroulard commented on shopinvader_search_engine_product_stock/models/se_index.py
> -# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Of course, I removed them by mistake.

2023-10-30 07:53 UTC, lmignon approved these changes

2023-11-02 10:18 UTC, sbejaoui approved these changes

2023-11-02 14:26 UTC, lmignon commented
/ocabot merge nobump

2023-11-02 15:40 UTC, lmignon commented
/ocabot merge nobump

2023-11-02 15:41 UTC, merged