[WIP][16.0][MIG] shopinvader_api_quotation
shopinvader/odoo-shopinvader pull request #1447
Opened 2023-11-07 08:56 UTC by matthieusaison

Migrate shopinvader_quotation to shopinvader_api_quotation with fastapi

2023-11-13 08:03 UTC, sebastienbeau commented on shopinvader_api_quotation/__manifest__.py
> +    "depends": ["crm", "fastapi", "shopinvader_schema_sale", "shopinvader_api_cart"],
this module should depend on shopinvader_api_security_sale and  shopinvader_schema_sale (crm, shopinvader_api_cart can be removed)

2023-11-13 08:04 UTC, sebastienbeau commented on shopinvader_api_quotation/models/sale_order.py
> +# from odoo.exceptions import UserError
remove comment

2023-11-13 08:33 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +class ShopinvaderApiQuotationquotationsRouterHelper(models.AbstractModel):
see : https://github.com/shopinvader/odoo-shopinvader/blob/16.0/shopinvader_api_sale/routers/sales.py

2023-11-13 13:04 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +from odoo.addons.fastapi.utils import FilteredDomainAdapter
from odoo.addons.shopinvader_filtered_model.utils import FilteredModelAdapter

2023-11-13 13:04 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +    # env["sale.order"]._confirm(order)
Todo remove comment

2023-11-13 13:04 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +
TODO add update

see: https://github.com/shopinvader/odoo-shopinvader/blob/b42cf29964111c8af6dad796d695342a5bfc62d3/shopinvader_api_cart/routers/cart.py#L57


The aim is to be able to update the client_order_ref

{"customer_ref": "PO_XXXX"}


spec:

```
@router.post("/quotations/{quotation_id}")
def update_quotation(
    data: QuotationUpdateInput,
    env: Annotated[api.Environment, Depends(authenticated_partner_env)],
    partner: Annotated["ResPartner", Depends(authenticated_partner)],
    quotation_id: int,
):

=> Sale.from_quotation(quotation)

```

2023-11-13 13:04 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/__init__.py
> +from . import quotation
TODO add a cart router


Extend Sale pydantic model
```
{
    "available_for_quotation": True,
    "shop_only_quotation": True/ False, (if we have a product shop_only_quotation in a sale order)
}
```


exemple: https://github.com/shopinvader/odoo-shopinvader/blob/b42cf29964111c8af6dad796d695342a5bfc62d3/shopinvader_api_cart/schemas/sale.py#L8



```
@router_cart.post("{uuid}/request_quotation")
def request_quotation(
    uuid: uuid
    env
    partner
)

return Sale.from_sale_order(order)

```

2023-11-14 08:49 UTC, matthieusaison commented on shopinvader_api_quotation/routers/__init__.py
> +from . import quotation
How is compute available_for_quotation? 
is it always True?

2023-11-14 22:15 UTC, sebastienbeau commented on shopinvader_api_quotation/models/product_template.py
> +    shop_only_quotation = fields.Boolean(
On V16 the following code will not work anymore (due to some ORM cleanup)
We should replace the boolean on the product_template by a "selection field" with the following value

```
   ("all_variant", "All Variant"),
   ("manually_on_variant", "Manually on Variant"),
   ("never", "Never"),
```


Then the inverse method will do the following

all_variant => all variant to True
manually_on_variant => do nothing
never => all variant to False

The compute method should do the following
all variant to True => all_variant
mix => manually_on_variant
all variant to False => never

So doing a recompute will be stable and the test will be not brokend anymore

2023-11-14 22:16 UTC, sebastienbeau commented on shopinvader_api_quotation/models/product_template.py
> +    shop_only_quotation = fields.Boolean(
we should also rename the field to "shop_only_quotation_mode" so we do not have "name" conflict between product and template

2023-11-14 22:20 UTC, sebastienbeau commented
After thinking twice, I think it will be great to create a base module "sale_quotation" will all the "odoo logic" (everything we have in the models + views and tests on product).

So shopinvader_quotation (use with restapi) and shopinvader_api_quotation can depend on it.

Also in a long term we can improve the flow of sale_quotation to add more feature so it can be totaly usable without any frontend implementation.

2023-11-20 10:25 UTC, sebastienbeau commented on shopinvader_api_quotation/views/product_view.xml
> +        <field name="inherit_id" ref="shopinvader.view_product_template_form" />
Todo move this field elsewhere

2023-11-21 10:36 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/cart.py
> +cart_router = APIRouter(tags=["carts"])
Do not redifine a new cart router
Use the existing one
```suggestion
from odoo.addons.shopinvader_api_cart.routers import cart_router
```
 from odoo.addons.shopinvader_api_cart.routers import cart_router

2023-11-21 10:36 UTC, sebastienbeau commented on shopinvader_api_quotation/schemas/sale.py
> +from extendable_pydantic import StrictExtendableBaseModel
The __ini__.py is missing in the directory schemas

2023-11-22 06:34 UTC, sebastienbeau requested changes

2023-11-22 06:34 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +    def _confirm(self, quotation):
```suggestion
    def _confirm(self, quotation_id):
```

2023-11-22 06:34 UTC, sebastienbeau commented on shopinvader_api_quotation/routers/quotation.py
> +    def _update(self, quotation, data):
```suggestion
    def _update(self, quotation_id, data):
```

2023-11-24 08:39 UTC, matthieusaison commented
I close this PR, and continue here  for a more readable work: https://github.com/shopinvader/odoo-shopinvader/pull/1471

2023-11-24 08:39 UTC, closed without merging