[16.0][IMP] shopinvader_schema_sale: sale_line qty rounding
shopinvader/odoo-shopinvader pull request #1503
Opened 2024-02-20 11:04 UTC by qgroulard

2024-03-20 12:25 UTC, lmignon approved these changes

2024-06-03 15:50 UTC, benwillig approved these changes

2024-06-03 16:56 UTC, lmignon commented
/ocabot merge patch

2024-06-03 17:00 UTC, lmignon requested changes

2024-06-03 17:00 UTC, lmignon commented on shopinvader_schema_sale/schemas/sale_line.py
> +            qty=float_round(
you must use `json_float_round`

2024-06-04 09:00 UTC, qgroulard commented on shopinvader_schema_sale/schemas/sale_line.py
> +            qty=float_round(
Done

2024-06-04 10:46 UTC, lmignon approved these changes

2024-06-04 10:46 UTC, lmignon commented
/ocabot merge patch

2024-06-04 10:52 UTC, merged