[16.0] shopinvader_product_sale_packaging: fix empty barcode
shopinvader/odoo-shopinvader pull request #1522
Opened 2024-03-25 16:06 UTC by simahawk

Never fail when a packaging has no barcode.
No matter where the data is coming from or how the object is initialized.

2024-04-02 08:04 UTC, mmequignon approved these changes

2024-04-05 05:57 UTC, cyrilmanuel approved these changes

2024-04-08 07:41 UTC, marielejeune reviewed
@simahawk Why not adding `or None` when building the `SimpleProductPackaging` here: 
https://github.com/shopinvader/odoo-shopinvader/blob/5552357a8a34ff4814a9cbf1cd2af75e91adfd6c/shopinvader_product_sale_packaging/schemas/product_packaging.py#L24

I think it was forgotten there.

2024-04-19 07:49 UTC, simahawk commented
> @simahawk Why not adding `or None` when building the `SimpleProductPackaging` here:
> 
> https://github.com/shopinvader/odoo-shopinvader/blob/5552357a8a34ff4814a9cbf1cd2af75e91adfd6c/shopinvader_product_sale_packaging/schemas/product_packaging.py#L24
> 
> I think it was forgotten there.

It's on purpose. That was my first fix but it won't work in all the cases.
That's why I added the comment "Ensure `barcode` is set to None when empty, no matter if we use `from_packaging`.".

2024-04-19 08:41 UTC, marielejeune commented
@simahawk I'm sorry but I'm not really into the code anymore 😅
Can you give an example where we don't use `from_packaging`?

2024-06-04 08:57 UTC, lmignon requested changes

2024-06-04 08:57 UTC, lmignon commented on shopinvader_product_sale_packaging/schemas/product_packaging.py
> +        super().__init__(**data)
It's not the right way to do it with pydantic. You should use the [field_validator](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) method.
```suggestion
from pydantic import field_validator


        @field_validator("barcode",  mode="before")
        @classmethod
        def barcode_none_when_empty(cls, v: Any):
            # Ensure `barcode` is set to None when empty, no matter if we use `from_packaging`.
             return v or None
```

2024-12-02 16:34 UTC, paradoxxxzero commented
@simahawk could you update this PR according to the requested changes please?

2024-12-09 08:56 UTC, paradoxxxzero commented
@simahawk After further investigation, I don't think I understand what this fix is trying to achieve. What are the cases not covered by @marielejeune fix?  Are you building `SimpleProductPackaging` instances directly? In which case why not putting an `or None` there too?

2025-05-18 12:23 UTC, closed without merging