shopinvader_product_media: fix active media exclusion
shopinvader/odoo-shopinvader pull request #1531
Opened 2024-04-11 07:46 UTC by mmequignon

Inactive media should be excluded from exported data.

NOTE: this is probably needed on image relations too ;)

2024-04-16 13:02 UTC, simahawk commented on shopinvader_product_media/tests/test_variant_media.py
> +    # FIXME
FIXME! :)
Eg: do not check for the count but for the right media to be in the list.

2024-04-16 13:02 UTC, simahawk commented on README.md
> +[shopinvader_product_manufactured_for](shopinvader_product_manufactured_for/) | 14.0.1.1.0 |  | Manage Product Made Specially For Some Customers
unrelated change

2025-04-01 17:43 UTC, simahawk commented
/ocabot merge patch

2025-05-13 15:15 UTC, lmignon commented
/ocabot merge patch

2025-05-14 06:18 UTC, lmignon commented
/ocabot merge patch

2025-05-14 06:53 UTC, lmignon commented on shopinvader_product_media/tests/__init__.py
> +from . import test_product_image_relation
@mmequignon It's not the right file.... 

```suggestion
from . import test_variant_media
```

2025-05-14 06:54 UTC, lmignon requested changes
see comment.

The error into the log could prevent the merge command to succeed.

2025-10-19 12:23 UTC, closed without merging