[16.0] [ADD] shopinvader_api_invoice
shopinvader/odoo-shopinvader pull request #1572
Opened 2024-12-03 09:18 UTC by paradoxxxzero

And shopinvader_schema_invoice, shopinvader_api_security_invoice.

Superseeds #1493 

Based on the work of @simahawk in #1493 with included requested changes, enum fixes, and use of new `report_generate_helper`.

2025-04-02 22:04 UTC, sebastienbeau requested changes

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_api_invoice/routers/invoice.py
> +    )
Can you move this in a helper of the router ? So we can inherit it correctly

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_api_invoice/routers/invoice.py
> +    )
same here

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_api_invoice/routers/invoice.py
> +    return record._generate_report("account.account_invoices")
apply a security domain before calling sudo
sudo danger !

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_api_security_invoice/security/acl_product_product.xml
> +</odoo>
If we use sudo (but with explicit check on domain) we can remove this rule

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_api_security_invoice/security/rule+acl_account_move.xml
> +    <field name="perm_write" eval="1" />
no need of create and write

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_schema_invoice/tests/common.py
> +    return type_dict.get(rec[field], rec[field])
This method are not used, we can remove them

2025-04-02 22:04 UTC, sebastienbeau commented on shopinvader_schema_invoice/tests/common.py
> +    """
this method should be move in the "class SchemaInvoiceCase"

2025-04-08 14:57 UTC, paradoxxxzero commented
@sebastienbeau refactored

2025-05-14 06:33 UTC, lmignon approved these changes

2025-05-14 06:47 UTC, lmignon commented
superseded by #1589 to be merged...

2025-05-14 06:47 UTC, closed without merging