16.0 ref cart address hooks
shopinvader/odoo-shopinvader pull request #1574
Opened 2024-12-09 10:27 UTC by paradoxxxzero

@simahawk, @lmignon Here's a proposal to address #1534 and #1536 in a cleaner way.

I don't think we should promote the use of envs in schema methods, IMO the schema methods should work on the schema data only and the router helpers should work as a joint layer between schemas and models.
 
This provides the requested hooks in helper classes in the form of the traditional inheritable prepare methods.

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +
AddressType = Literal["invoicing", "delivery"]

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        self, address_id: int, address_type: Literal["invoicing", "delivery"]
```suggestion
        self, address_id: int, address_type: AddressType 
```

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        address_type: Literal["invoicing", "delivery"],
```suggestion
        address_type: AddressType,
```

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        address_type: Literal["invoicing", "delivery"],
```suggestion
        address_type: AddressType,
```

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        address_type: Literal["invoicing", "delivery"],
```suggestion
        address_type: AddressType,
```

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        address_type: Literal["invoicing", "delivery"],
```suggestion
        address_type: AddressType,
```

2024-12-09 12:30 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        address_type: Literal["invoicing", "delivery"],
```suggestion
        address_type: AddressType,
```

2024-12-09 14:46 UTC, paradoxxxzero commented on shopinvader_api_address/routers/address_service.py
> +
Make sense, thanks!

2025-04-01 16:14 UTC, sebastienbeau approved these changes
LGTM (code review)
seem to be cleaner to have this prepare method instead of hacking the schema

@simahawk @lmignon ok for you ?

2025-04-01 16:29 UTC, lmignon requested changes

2025-04-01 16:29 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        return getattr(
We should never return something from a method called with `sudo` it's a potential security breach

2025-04-01 16:29 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +        return getattr(
We should never return something from a method called with `sudo` it's a potential security breach

2025-04-01 16:29 UTC, lmignon commented on shopinvader_api_address/routers/address_service.py
> +            self.partner.sudo(), f"_update_shopinvader_{address_type}_address"
This kind of approach makes the code hard to analyse and refactor. I really prefer explicit call to the appropriate method.

2025-04-02 15:17 UTC, paradoxxxzero commented on shopinvader_api_address/routers/address_service.py
> +        return getattr(
Indeed

2025-04-02 15:18 UTC, paradoxxxzero commented on shopinvader_api_address/routers/address_service.py
> +            self.partner.sudo(), f"_update_shopinvader_{address_type}_address"
And more code is more code to refactor but fair enough

2025-04-02 15:24 UTC, paradoxxxzero commented
I added the requested fixes

2025-04-02 16:28 UTC, lmignon approved these changes

2025-04-02 18:21 UTC, sebastienbeau commented
Thanks for your work !

/ocabot merge patch

2025-04-02 18:35 UTC, merged