[16.0] [IMP] shopinvader_api_cart: Make cart transaction grouping extendable
shopinvader/odoo-shopinvader pull request #1575
Opened 2024-12-16 17:05 UTC by paradoxxxzero

2025-04-01 15:08 UTC, sebastienbeau approved these changes
LGTM (code review) and tested.
Work in production since several month.

I think we can merge it @lmignon

2025-04-01 16:40 UTC, lmignon commented on shopinvader_sale_cart/models/sale_order.py
> +            line = self._get_cart_line(**cart_line.read(load=False)[0])
Why a `read`?  and why 'load=False`?

2025-04-01 16:45 UTC, lmignon requested changes

2025-04-01 16:45 UTC, lmignon commented on shopinvader_sale_cart/models/sale_order.py
> +                vals = cart_line._prepare_cart_line_transfer_values()
Despite the docstring on this new method, I don't understand its purpose/meaning. Here we update the line and you mix it the concept of ?transfer? Once again you use a method designed for a specific context into another one. It's not safe.

2025-04-01 16:45 UTC, lmignon commented on shopinvader_api_cart/routers/cart.py
> +                **self._apply_transactions_creating_new_cart_line_prepare_vals(
Why do you request the preparation of values required to create a line to lookup for an existing line. IMO it's a bad practice to reuse method designed with a specific purpose into another context.

2025-04-02 18:10 UTC, sebastienbeau commented on shopinvader_sale_cart/models/sale_order.py
> +                vals = cart_line._prepare_cart_line_transfer_values()
Hi Laurent, maybe the issue is the more the naming of "_update_cart_lines_from_cart" (the method where we are in)
This method will transfer the line of a cart passed in args to the current cart (self).
This why @paradoxxxzero have put the key word "transfer" for this prepare method.
Maybe a better name will be "_transfer_cart_lines_from_cart" or  "_transfer_lines_from_cart" ? What do you think ?

2025-04-02 18:10 UTC, sebastienbeau commented on shopinvader_api_cart/routers/cart.py
> +                **self._apply_transactions_creating_new_cart_line_prepare_vals(
Thanks for your precious review !
Indeed reusing existing method make the code harder to understand.

I think we will need your help for getting the right solution.

Let's explain why we did that, it will also explain the "read(load=False)"




The get_cart_line is used in 2 different context

- get a cart line from transaction information  (case adding something in a cart)
- get a cart line from an other cart line (case of merging cart)

Before only one param was pass ("product_id") now we want to make it customizable

@paradoxxxzero have try to find a solution that limit the number of method to extend when you add some option.

We though about 3 solutions to pass as param to get_cart_line


## Passing a "key"
This can be a namedTuple, a hash or something else) and then having 2 methods 
  - _prepare_line_key (on the sale.order.line)
  - _prepare_line_key_from_transaction_key (in the helper of the router)

Then when you add the support of option you need to inherit
  - _prepare_line_from_transactions (to convert data to sale.order.line vals)
  - _prepare_line_key
  - _prepare_line_key_from_transaction_key


Matching "line" and "transaction" or "line" and "line" can be done with a generic implementation as we compare this 2 key

## Passing a "sale.order.line"
In that case the idea is to create a "new" line¹ and then compare "sale.order.line" with "sale.order.line"

¹ For creating a "new" line the idea is to call the _apply_transactions_creating_new_cart_line that return the vals of the (sale.order.line) from the transaction

Then when you add the support of option you need to inherit
  - _prepare_line_from_transactions (to convert data to sale.order.line vals)
  - the _match_cart_line (to add additional condition compare a sale.order.line and a sale.order.line)


One thing here, is that it fell weird to call the method _get_cart_line with a params that is a "line". I not sure it's easy to understand


## Passing a dict of vals that represent a "sale.order.line"
In that case the idea is to always call the _get_card_line with a dict that represent a sale.order.line

get_cart_line from a line => we generate a dict using the "read"² method on the "sale.order.line" 
get_cart_line from a transaction => we generate a dict using the existing prepare method


² The option load=False is set as for partner_id we expect {"partner_id": 3} and not  {"partner_id": (3, "John Doe")}

Then when you add the support of option you need to inherit
  - _prepare_line_from_transactions (to convert data to sale.order.line vals)
  - the _match_cart_line (to add additional condition to compare a sale.order.line and dict of vals that represent a sale.order.line)

The last option was our favorite (less code to inherit) and passing "vals" to get_cart_line seem more natural


I will try to think twice, if we found a better one, @lmignon if you have some time tomorrow we can have a meet

2025-04-02 18:10 UTC, sebastienbeau commented on shopinvader_sale_cart/models/sale_order.py
> +                vals = cart_line._prepare_cart_line_transfer_values()
After think twice maybe we can simplify the code, but the impact is that a cart transfer will "destroy" the original one (is what we do now in the router)

```
class SaleOrderLine():

    def _update_line_after_transfer(self):
        self._compute_tax_id()
        self._compute_price_unit()
        self.discount = 0.0
        self._compute_discount()
```
Then in this method we can do something like
```
else:
    cart_line.order_id = self
    cart_line._update_line_after_transfer()
```

So we do not have to inherit "_prepare_cart_line_transfer_values" for transferring option.

Not sure if it's a good idea but I do not see the case where we want to keep the original cart.
Keeping it will need to generate addition code to inherit for the transfer of option

2025-04-02 18:18 UTC, sebastienbeau commented on shopinvader_api_cart/routers/cart.py
> +                **self._apply_transactions_creating_new_cart_line_prepare_vals(
After think twice maybe we should move this logic of "merging" cart in a generic OCA module "sale_order_merge" ?
Basically merge a sale into an other sale or merging a cart into an other cart is the same thing ?
What do you think ?

2025-04-03 08:26 UTC, lmignon commented on shopinvader_api_cart/routers/cart.py
> +                **self._apply_transactions_creating_new_cart_line_prepare_vals(
Merging a cart/so into another is out o the scope of the management of transactions on a cart. Your changes makes the code difficult to read/understand. If your need to merge a SO/cart,  it's not the purpose of this addon and should be implemented in a generic way out of the scope of the cart api (IMO).

2025-05-13 12:28 UTC, lmignon approved these changes

2025-05-13 12:29 UTC, lmignon commented
/ocabot merge minor

2025-05-13 14:27 UTC, lmignon commented
/ocabot merge minor

2025-05-13 14:35 UTC, merged