[IMP] show discount if set on pricelist
shopinvader/odoo-shopinvader pull request #186
Opened 2018-08-20 13:57 UTC by bguillot

2018-08-22 15:36 UTC, lmignon requested changes

2018-08-22 15:36 UTC, lmignon commented on shopinvader/models/shopinvader_variant.py
> +        if pricelist.discount_policy == 'without_discount':
@bguillot IMO this changes requires a unittest....

2018-08-22 15:43 UTC, lmignon requested changes

2018-08-22 15:43 UTC, lmignon commented on shopinvader/models/shopinvader_variant.py
> +            new_list_price, currency_id = self.env['sale.order.line']._get_real_price_currency(product, rule_id, qty or 1.0, product.uom_id, pricelist.id)
Is the tax included or not into this new_list_price? 
We must also take into account the fiscal_position. 
I've the feeling that the result of this method will be wrong... But I hope I'm wrong...

2018-09-11 08:51 UTC, lmignon commented on shopinvader/models/shopinvader_variant.py
> +            new_list_price, currency_id = self.env['sale.order.line']._get_real_price_currency(product, rule_id, qty or 1.0, product.uom_id, pricelist.id)
I'm now sure I'm right :smirk: see https://github.com/akretion/odoo-shopinvader/pull/207/commits/59054bde505da541d53c776942e5c84813563f23

2018-09-11 08:54 UTC, lmignon commented
@sebastienbeau @bguillot This once can be closed. I've fixed the code to take into account the fiscal postion (tax mapping) and the digital precision to apply to discount in the computation of the original price and discount. I've also added tests to cover the different cases when computing the price (price list with and without discount, price list with and wihtout discount policy, fiscal position with and without tax mapping)

2018-09-11 10:05 UTC, closed without merging

2018-09-11 10:05 UTC, sebastienbeau commented
Close pull request as this have been done here : https://github.com/akretion/odoo-shopinvader/pull/207