merge branch 8.0
shopinvader/odoo-shopinvader pull request #2
Opened 2016-10-26 14:02 UTC by EBII

2016-10-26 14:09 UTC, sebastienbeau requested changes

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/LICENSE
> +GNU AFFERO GENERAL PUBLIC LICENSE
Pas besoin de mettre la licence dans chaque module tu peux la mettre a la racine ça suffit

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/README
> +# -*- encoding: utf-8 -*-
pas besoin de ce fichier

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/__openerp__.py
> +# -*- encoding: utf-8 -*-
le header n'est pas correct regarde le template de l'oca

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/__openerp__.py
> +    #les screenshots en v8: mettre dans static/description/, sans déclaration
il faut enlever les commentaires

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/model.py
> +# -*- coding: utf-8 -*-
il faut ajouté le header

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/model.py
> +        sauvegarder ancienne url si exist et
pas de docstring en français

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/model.py
> +        #import pdb; pdb.set_trace()
enlevé le code commenté

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/model.py
> +        _logger.info("model referencé : %s ", model_ref)
pas de logger en français

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/model.py
> +tester changement de nom produit : > nouvell url
enlevé commenatire en français

2016-10-26 14:09 UTC, sebastienbeau commented on base_url/tests/test_UN.py
> +class TestalaCon(unittest.TestCase):
il faudra reprendre le nom des tests ;)

2016-10-31 10:24 UTC, sebastienbeau commented on base_url/model.py
> +            if len(search_key) < 2:
Note le cas avec plus de 2 url ne devrait jamais exister, la contraite sql est fait pour ça.

2016-11-03 14:17 UTC, bealdav requested changes

2016-11-03 14:17 UTC, bealdav commented on base_url/LICENSE
> +GNU AFFERO GENERAL PUBLIC LICENSE
perso, sauvons le cloud et les bb phoques, ceux sont des octets qui réchauffent la planète et n'apportent rien o module.
mais juste perso.

2016-11-03 14:17 UTC, bealdav commented on base_url/__openerp__.py
> +
utiliser la version courte indiqué dans les guidelines

2016-11-03 14:17 UTC, bealdav commented on base_url/__openerp__.py
> +    'name': 'base_url',
Mettre 'Base Url'. C'est le nom du dossier qui compte pour Odoo. Pensons user friendly / market place

2016-11-03 14:17 UTC, bealdav commented on base_url/__openerp__.py
> +    'application': False,
remove the 2 keys above

2016-11-03 14:17 UTC, bealdav commented on base_url/README.rst
> +This module extends the functionality of ... to support ...
rubrique vitale, merci de compléter

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +# -*- coding: utf-8 -*-
guideline header sur chaque fichier

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +                                readonly=True,
- manque l'arg 'string' ce qui fait qu'on model_id dans l'ui
- le help mérite d'etre plus consistant (1 ligne complète est bienvenue)
- ce n'est pas un model mais 1 record je crois

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +    redirect = fields.Boolean('Redirect')
missing 'help'

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +    _sql_constraints = [("urlurl unique key",
s/urlurl unique key/url unique key   car c un 1 nom

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +        return []
s/_reference_models/_referencable_models   ou 1 truc du genre

2016-11-03 14:17 UTC, bealdav commented on base_url/models/model.py
> +    url_key = fields.Char(string="Url Id", store=True)
- par défaut il est déjà True un field Char, à enlever
- s/Url Id/Url

2016-11-03 14:17 UTC, bealdav commented on product_url/models/model.py
> +                ('product.category', "Category")]
Perso j'utilise ' pour les infos courtes
    et " pour les infos longues.
Tout le monde ne fait pas comme ça, mais tout le monde est constant, fix it

2016-11-03 14:17 UTC, bealdav commented on product_url/demo/url.url.csv
> +5,"product.template,2",monitoring bourré,False
english humor please

2016-11-03 14:17 UTC, bealdav commented on product_url/__openerp__.py
> +    'url': '',  # ??
Used key by Odoo

2016-11-03 14:17 UTC, bealdav commented on product_url/__openerp__.py
> +    # v9: ./static/description/icon.png
remove comment

2016-11-03 14:42 UTC, bealdav requested changes

2016-11-03 14:42 UTC, bealdav commented on base_url/__openerp__.py
> +        'bin': [],
not used, remove

2016-11-03 14:42 UTC, bealdav commented on base_url/models/model.py
> +                                           comodel_name="url.url")
- s / redirect_url_key_ids / url_redirect_key_ids
- missing 'inverse_name' arg

2016-11-03 14:42 UTC, bealdav commented on base_url/models/model.py
> +                          inverse="_inverse_set_url", string="Url key")
- s / Url key / Url Key
- missing 'help' arg

2016-11-03 14:42 UTC, bealdav commented on base_url/models/model.py
> +# -*- coding: utf-8 -*-
s / model.py / url.py

2016-11-03 14:42 UTC, bealdav commented on base_url/tests/test_un.py
> +        self.assertEqual('foo'.upper(), 'FOO')
Why these tests ?

2016-11-03 14:42 UTC, bealdav commented on base_url/views/url_view.xml
> +
saut de ligne inutile

2016-11-03 14:42 UTC, bealdav commented on base_url/views/url_view.xml
> +
<record pas aligné avec précédent

2016-11-03 14:42 UTC, bealdav commented on base_url/views/url_view.xml
> +        <field name="name">url list Viewer</field>
pour viewer ? on peut pas modifier ?

2016-11-03 14:42 UTC, bealdav commented on base_url/views/url_view.xml
> +        <record id="base_url_action_view" model="ir.actions.act_window">
s / base_url_action_view / base_url_action     car c 1 action pas une vue

2016-11-03 14:42 UTC, bealdav commented on product_url/README.rst
> +To install this module, you need to:
manque description

2016-11-03 14:42 UTC, bealdav commented on product_url/__openerp__.py
> +    'summary': 'keep history of url for product & categorie  ',
s / for product & categorie / for products & categories

2016-11-03 14:42 UTC, bealdav commented on product_url/__openerp__.py
> +    'website': 'https://www.akretion.fr',
https://www.akretion.com/fr

2016-11-03 14:42 UTC, bealdav commented on product_url/models/model.py
> +# -*- coding: utf-8 -*-
le dossier s'appel model, le fichier pourrait s'appeler url ou product

2016-11-03 14:42 UTC, bealdav commented on product_url/tests/test_two.py
> +
utiliser TransactionCase qui est une surcharge de unittest

2016-11-03 14:42 UTC, bealdav commented on product_url/tests/test_two.py
> +if __name__ == '__main__':
pas utile, le test est appelé quand meme pas le framework odoo

2016-11-03 14:42 UTC, bealdav commented on product_url/tests/test_two.py
> +            s.split(2)
test pas trop utile pour ton use case

2016-11-03 14:42 UTC, bealdav commented on product_url/tests/test_un.py
> +        self.assertEqual('foo'.upper(), 'FOO')
pas trop utile

2016-11-03 14:42 UTC, bealdav commented on product_url/views/product_view.xml
> +                                    <field name="redirect_url_key_ids"/>
affiche la vue par défaut du o2m.
Là on ne veut pas la colonne model_id (mettre à invisible) car il ne fait que répéter le nom du produit

2016-11-03 14:42 UTC, bealdav commented on product_url/views/product_view.xml
> +
mise en page améliorable

2016-11-03 15:54 UTC, bealdav requested changes

2016-11-03 15:54 UTC, bealdav commented on product_url/tests/test_url.py
> +        product = self.env['product.template'].browse(9)
pas d'id pour les produits, trouver l'xml id

2016-11-03 15:54 UTC, bealdav commented on product_url/views/product_view.xml
> +                        <page string="Rewrite url">
quand tu as beaucoup d'onglet ça rentre plus
je suggère Url

2016-11-03 15:54 UTC, bealdav commented on base_url/models/model.py
> +    def _get_object(self, urls):
urls est un itérable (list, etc) ?
- si oui ("url_key", "in", urls)
- si non s / urls / url

2016-11-03 15:54 UTC, bealdav commented on base_url/models/model.py
> +        object = self.search([("url_key", "=", urls)]).model_id
que se passe-t-il la recherche vaut False ?

2016-11-03 15:54 UTC, bealdav commented on base_url/models/model.py
> +        return object
on pourrait faire directment return self.search([("url_key", "=", urls)]).model_id

2016-11-03 15:54 UTC, bealdav commented on base_url/models/model.py
> +        if name is None:
inverser la condition permet de mettre : 
`if name:`  au lieur de  `if name is None:`

2016-11-03 15:54 UTC, bealdav commented on base_url/models/model.py
> +            url_key = slugify(url_to_normalize)
pourquoi une var intermédiaire ?

2016-11-03 16:07 UTC, bealdav requested changes

2016-11-03 16:07 UTC, bealdav commented on base_url/models/model.py
> +                        'message': 'it will will be adapted to %s' % (url)}}
au niveau usability, je pense que c 1 peu lourd. Je ferais pas de warning ; voir avec seb

2016-11-03 16:07 UTC, bealdav commented on base_url/models/model.py
> +        url = self._prepare_url(self.url_key)
en theorie c mieux avec for record in self:
même si l'editeur ne le fait pas mais tu l'as fait dans la fct précedente

2016-11-03 16:07 UTC, bealdav commented on base_url/models/model.py
> +            .search([('model_id', '=', model_ref), ('redirect', '=', True)])
sans doute un gout personnel, mais trop de saut de ligne nuit à la lisibilité de l'ensemble du script
=> 2 lignes vides pas vraiment utiles ?

2016-11-03 16:07 UTC, bealdav commented on base_url/models/model.py
> +
?

2016-11-04 17:08 UTC, EBII commented on base_url/models/model.py
> +                        'message': 'it will will be adapted to %s' % (url)}}
no it is hope that you write tùttù and it was change so we choose to prompt the user about the change ..

2016-11-07 13:15 UTC, bealdav commented on base_url/__openerp__.py
> +
tu est sur que tu as répondu aux points de la PR ?

2016-11-07 13:15 UTC, bealdav commented on base_url/__openerp__.py
> +        'bin': [],
car je suis pas sur que soit allé jusqu'au bout

2016-11-07 13:15 UTC, bealdav commented on base_url/models/model.py
> +# -*- coding: utf-8 -*-
le but est que le reviewer perde le moins de temps possible il faut finir le boulot à 105 %

2016-11-07 13:27 UTC, EBII commented on base_url/models/model.py
> +        return []
no same idea but short

2016-11-07 13:30 UTC, EBII commented on base_url/models/model.py
> +# -*- coding: utf-8 -*-
seems ok

2016-11-07 13:39 UTC, EBII commented on product_url/README.rst
> +To install this module, you need to:
si ligne 9

2016-11-07 14:14 UTC, EBII commented on product_url/tests/test_un.py
> +        self.assertEqual('foo'.upper(), 'FOO')
a mieux voir passer le test,

2016-11-07 14:15 UTC, EBII commented on base_url/models/model.py
> +    def _get_object(self, urls):
ok url

2016-11-07 15:31 UTC, bealdav commented on product_url/tests/test_un.py
> +        self.assertEqual('foo'.upper(), 'FOO')
pas compatible OCA, dsl

2016-11-07 15:31 UTC, bealdav commented on product_url/__openerp__.py
> +##############################################################################
A 3 lignes près (à supprimer) on y est :-)

2016-11-07 15:31 UTC, bealdav commented on product_url/README.rst
> +To install this module, you need to:
cela ne me dit rien sur ce que fait le module. Encore moins à ceux qui le verront sur l'app store.

2016-11-07 15:31 UTC, bealdav commented on product_url/README
> +# -*- encoding: utf-8 -*-
fichier inutile

2016-11-08 18:07 UTC, sebastienbeau requested changes

2016-11-08 18:07 UTC, sebastienbeau commented on .gitignore
> +Brouillons.txt
bizarre de mettre cette ligne la, a mon avis il serait mieux de la mettre dans ton gitignore perso (qui est global en plus)

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +        this_model_urls = self.env['url.url'].search([
il faudrait mettre un nom de variable plus explicite
genre redirect_urls = ...

tu peux éviter du temps de traitement inutile en ajoutant ('redirect', '=', False) dans le filtre car ceux qui sont déjà a true ça sert a rien de les retraiter

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +            for model in already_exist_url.model_id:
le for n'est pas utile ici car
1 - si jamais il y avait plusieurs élément suite a la recherche alors la liste serait already_exist_url donc le already_exist_url.model_id remontrait un message d'erreur. il aurait plutôt fallut écrire
for url in already_exist_url: 
    url.model_id.....
....
2- ce cas n'est pas possible car il y a une contrainte sql qui empeche d'avoir plus de 2 urls

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +            model_ref = "%s,%s" % (record._name, record.id)
ce code est répété a plusieurs endroits. Malheuresement il n'y a pas de méthode magique dans odoo. Par contre pour faire plus propre ça peut etre mieux de faire une méthode dans AbstractUrl genre 

def _get_reference(self):
    return "%s,%s" % (self.name, self.id)

comme ça le jour ou odoo change pour une "," à un ";" et bien c'est plus clean a mettre a jour

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +                record.url_key = url[0].url_key
le url[0] ne sert a rien car tu retourne tjs qu'un seul élement (voir contrainte sql). Il faut mieux mettre un url tout court car si il y en a plus c'est qu'on a un bug et donc ça plantera au lieu de rien dire

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +        url_key = 'prepare'
a mon avis cette variable est un truc de test

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +                url = record._prepare_url(record.url_key)
je pense pas qu'il faille utilise la meme méthode prepare_url, car en regardant la méthode tu fini par mettre un if pour traiter différement le cas des name et des urlkey.

A mon avis il faut utiliser la méthode prepare uniquement dans le cas du onchange sur les noms.

Dans le cas du onchange sur les url tu peux simplement faire ça
new_url = slugify(record.url_key)
if new_url != record.url_key:
   record.url_key = new_url
   return {...warning...}


De plus la méthode prepare ne doit pas prendre d'argument en parametre, on a déjà accès a l'object avec toute les valeurs

2016-11-08 18:07 UTC, sebastienbeau commented on base_url/models/base_url.py
> +                record.url_key = url
ligne non utile car si l'url est identique ça sert a rien de réengistrer la valeur en db

2016-11-08 18:07 UTC, sebastienbeau commented on product_url/README.rst
> +* Firstname Lastname <email.address@example.org>
pense a mettre ton nom + mail

2016-11-08 18:07 UTC, sebastienbeau commented on product_url/__openerp__.py
> +##############################################################################
regarde dans le template de l'oca, l'année est fausse ;)

2016-11-08 18:07 UTC, sebastienbeau commented on product_url/models/product_url.py
> +
saut de ligne pas utile

2016-11-08 18:08 UTC, sebastienbeau commented
Des petites remarques mais ça avance, ça sera un joli module

2016-11-09 13:52 UTC, EBII commented on base_url/models/base_url.py
> +            model_ref = "%s,%s" % (record._name, record.id)
ok sauf que c'est bien _name et pas name la valeur souhaité...;o)

2016-11-09 13:52 UTC, EBII commented on base_url/models/base_url.py
> +                record.url_key = url[0].url_key
attention les category passe en listes je vais voir

2016-11-09 16:06 UTC, bealdav requested changes

2016-11-09 16:06 UTC, bealdav commented on product_url/views/category_view.xml
> +                            </group>
Reformate ce fichier, stp

2016-11-09 16:06 UTC, bealdav commented on product_url/__openerp__.py
> +##############################################################################
ligne 2, 3, 8 et 9 à supprimer.
Pourquoi différer du template de base ?

2016-11-09 16:06 UTC, bealdav commented on base_url/__openerp__.py
> +##############################################################################
some lines to remove, see below

2016-11-09 16:06 UTC, bealdav commented on base_url/README.rst
> +=============
If no configuration, remove useless blocks

2016-11-09 16:06 UTC, bealdav commented on base_url/README.rst
> +==============
why { ?

2016-11-09 16:06 UTC, bealdav commented on .gitignore
> +*~
missing break line

2016-11-09 16:06 UTC, bealdav commented on product_url/tests/__init__.py
> +from . import test_product, test_category
split into 2 lines (OCA recommandation for better traceability when changes)

2016-11-09 16:07 UTC, bealdav commented
Some minor remarks here. Thanks to fix it. After OK for me

2016-11-10 14:56 UTC, EBII commented on .gitignore
> +*~
ok

2016-11-10 15:00 UTC, bealdav approved these changes

2016-11-22 14:53 UTC, closed without merging