[10.0] guest mode
shopinvader/odoo-shopinvader pull request #231
Opened 2018-10-19 16:11 UTC by lmignon

This addons add a new option on the Shopnvader backend to allow to sale orders
in guest mode. The guest mode is a special case on the ecommerce website where
the customer is allowed to create a sale order without creating of a user
account on the website.

Into Odoo this results in the creation of a partner + binding with a fixed
validity period linked to the sale order. At the end of this period, the
binding is automatically disabled if the customer has not created an account.

It's not possible to create a new customer with the same email if a binding is
valid. In such a case the customer must create an account

If a customer create a new sale order in guest mode with the
same email, the new partner will be linked to the first partner found with
the same email except if shopinvader is configured to avoid duplicate partners

2018-10-19 16:13 UTC, lmignon commented
ping @sebastienbeau

2018-10-21 01:34 UTC, rvalyi commented on shopinvader_guest_mode/README.rst
> +This addons add a new option on the Shopnvader backend to allow to sale orders
s/add/adds/

2018-11-29 15:39 UTC, Cedric-Pigeon requested changes

2018-11-29 15:39 UTC, Cedric-Pigeon commented on shopinvader_guest_mode/models/shopinvader_partner.py
> +    @api.constrains('is_guest', 'backend_id.is_guest_mode_allowed')
You can only define constraints related to field directly on the object

2018-12-20 13:53 UTC, sebastienbeau reviewed
Thanks for your work and to the simple but great idea to create a "guest" customer to reuse the same flow.
There is just some like extra point

- maybe it will be simpler to delete the shopinvader.partner instead of archiving it? (no code for partial index and no need to change the constraint?). I am hesitating on this point. On own side code is simpler, 

No blocking point for this PR:

- we need a method/code to be able to send a token by mail (for example in the mail of the sale notification or in a specific mail) to be able to send a unique link so the customer can create an account latter.

- on ruby side I thinks we can "protect" the method register (we do not need to expose it in the proxy)

- we need to review the way to reset the password. Indeed if a customer go on locomotive and request for a password recovery we should request odoo for sending a specific message to inform him that his account is no created yet but if he click on the following link to set his password. For this last point maybe it will be easier and more consistent to always send the email from odoo. Locomotive can call odoo (with a reset_token if the account exist on locomotive, and without token in case of none existing cusomer).

Idea of improvement
- If we always send the email of reset password from odoo, an improvement for GRPD is maybe to not store the email in clear on locomotive side. Indeed we can store the sha of the email, it's enough to be able to login (we compare the hash of the email) and we send this hash to odoo in the "shopinvader session" so everything will still work. What do you think?

2018-12-20 13:53 UTC, sebastienbeau commented on shopinvader_guest_mode/README.rst
> +<https://github.com/OCA/{project_repo}/issues>`_. In case of trouble, please
we just need to change/remove this parts as this is not an OCA module

2018-12-20 13:53 UTC, sebastienbeau commented on shopinvader_guest_mode/services/guest_service.py
> +    def stop(self, email):
quit or logout ? is maybe a better name ?

2018-12-20 13:53 UTC, sebastienbeau commented on shopinvader_guest_mode/services/guest_service.py
> +        resp['store_cache']['customer']['is_guest'] = True
Maybe we can move the "is_guest" information directly in the mapping? So we will always have this key with False or True in the customer variable.

2018-12-20 14:03 UTC, lmignon commented on shopinvader_guest_mode/services/guest_service.py
> +    def stop(self, email):
we stop the guest mode... :smirk:

2018-12-20 14:08 UTC, lmignon commented
> maybe it will be simpler to delete the shopinvader.partner instead of archiving it? (no code for partial index and no need to change the constraint?). I am hesitating on this point. On own side code is simpler,

That was my first but I no more remember why I finally implemented the 'active' approach...

2019-03-23 15:48 UTC, merged