[10.0][ADD] Add URL bind/unbind for shopinvader.variant
shopinvader/odoo-shopinvader pull request #236
Opened 2018-11-08 08:55 UTC by acsonefho

**Expected behaviour**
- During shopinvader.variant unbind (`active = False`), edit related url.url to the first `shopinvader.category` without children (set as a redirection);
- During the opposite action (`active = True`) we have to delete every redirection then force the regeneration of urls;
- Into the `url.url` create, check if there already has some redirection (with same url, backend and lang) and remove them if necessary;

**Bonus**
- Fix compute for `url_url_ids` field (into `abstract.url`)

2018-11-12 10:31 UTC, Cedric-Pigeon approved these changes
Code review

2018-11-12 10:32 UTC, Cedric-Pigeon commented
@sebastienbeau @lmignon Could you have a look at this one ?

2018-12-21 16:22 UTC, lmignon commented on shopinvader_locomotive/models/shopinvader_variant.py
> +        Inherit to call the delete on locomotive if the recordset is un-binded.
@acsonefho This comment should be wrong since no variant are exported to locomotive...

2018-12-21 16:24 UTC, lmignon requested changes
@acsonefho Can you rebase PLZ. At first read LGTM

2019-04-14 13:34 UTC, sebastienbeau commented
This have been merged here : https://github.com/akretion/odoo-shopinvader/pull/296

2019-04-14 13:36 UTC, closed without merging