[10.0][IMP] shopinvader locomotive change password
shopinvader/odoo-shopinvader pull request #259
Opened 2018-12-12 16:33 UTC by hparfr

Should be merged after #255 

Change locomotiveCMS password from a wizard instead of directly in the form view.
![screenshot_2018-12-12 demo shopinvader backend - odoo](https://user-images.githubusercontent.com/8331206/49883932-f448d080-fe33-11e8-83fe-262f82dedcdf.png)
![screenshot_2018-12-12 demo shopinvader backend - odoo 1](https://user-images.githubusercontent.com/8331206/49883959-0296ec80-fe34-11e8-86aa-db7d29111353.png)

2019-04-01 14:02 UTC, lmignon commented on shopinvader_locomotive/models/shopinvader_backend.py
> +class ChangePasswordWizard(models.TransientModel):
this wizard is already declared into /wizard/change_password.py

2019-04-01 14:02 UTC, lmignon commented on shopinvader_locomotive/wizard/__init__.py
> +from . import change_password
directory should be `wizards`

2019-04-01 14:04 UTC, lmignon requested changes

2019-04-01 14:04 UTC, lmignon commented on shopinvader_locomotive/wizard/change_password.py
> +class ChangePasswordWizard(models.TransientModel):
The name of the module should be `shopinvader....`
The name of the class should be `ShopinvaderChange...`
The name of the file should be `shopinvader_shange....py`

2019-04-02 07:14 UTC, sebastienbeau commented
Not sure it worth the complexity.
In 12 most of people will use server env and for keychain user I plan to add a generic wizard.
So this will be only usable for user that do not use keychain and not server env.
Note we are going to try to have the maximun code in commun between the two version

2019-04-03 07:37 UTC, lmignon commented
@sebastienbeau @hparfr I propose to close this PR since the way pwd are managed will change

2019-04-05 12:13 UTC, closed without merging

2019-04-09 15:33 UTC, hparfr commented
I think it's even better to never let the user define this password.
It should be generated by odoo. And better pushed to rails.

@sebastienbeau If you wan't to keep the broken UI design for v10, I'm happy with that ;-)