10 shopinvader backend search tab
shopinvader/odoo-shopinvader pull request #261
Opened 2018-12-13 08:32 UTC by mourad-ehm

2018-12-13 08:59 UTC, bealdav commented on shopinvader_search_engine/models/se_index.py
> +    is_valide = fields.Char(compute='_compute_is_valide')
Why is it a Char and not boolean ?

s/is_valide/is_valid

2018-12-13 09:01 UTC, hparfr commented on shopinvader_search_engine/models/se_index.py
> +            active_id = self.env['shopinvader.backend'].browse(active_id)
should be put outside the for in self

2019-01-03 10:18 UTC, lmignon requested changes

2019-01-03 10:18 UTC, lmignon commented on shopinvader_search_engine/models/shopinvader_backend.py
> +                    ir_export = ir_export_obj.search([('resource', '=', model.model)])
@mourad-ehm More than one 'ir.export' can be defined for same model.... `limit=1`

2019-04-01 13:51 UTC, lmignon commented
conflicts resolved and code fixed

2019-04-02 12:31 UTC, merged