WIP [10.0][ADD] add module shopinvader_delivery_note
shopinvader/odoo-shopinvader pull request #313
Opened 2019-05-08 14:29 UTC by acsonefho

Create a module to let user define a delivery note (for cart).

2019-05-09 04:26 UTC, Cedric-Pigeon approved these changes

2019-05-10 05:57 UTC, lmignon requested changes

2019-05-10 05:57 UTC, lmignon commented on shopinvader_delivery_note/models/sale_order.py
> +class SaleOrder(models.Model):
@acsonefho IMO this code and the one into shopinvader_delivery_note should go into an new OCA addons: sale_delivery_note. It's not the intend of shopinvader to provide custom functionalities. Shopinvader must remains a service layer on top of business addons...

2019-08-29 07:58 UTC, lmignon commented
@acsonefho This PR depends on others PRS. It seems that these others PRS are waiting for your input. My main concern is about https://github.com/OCA/stock-logistics-workflow/pull/524#issuecomment-491294263
It seems that you've developed new addons for functionality already provided by an existing one. Therefore this enhancement should be based on the existing one...

2019-09-19 13:32 UTC, lmignon requested changes

2019-09-19 13:32 UTC, lmignon commented on shopinvader_delivery_note/services/cart.py
> +        validator.update({"picking_note": {"type": "string"}})
@acsonefho the customer specify a 'delivery_note' the picpcking is for the preparation. This field should be named 'delivery_note'

2019-09-19 13:32 UTC, lmignon commented on shopinvader_delivery_note/services/cart.py
> +    def _prepare_picking_note(self, picking_note, params):
s/picking/delivery

2019-09-19 15:36 UTC, lmignon approved these changes

2019-09-19 15:53 UTC, lmignon commented
Once merged we must create an issue to forward port this PR into 12.0 Nevertheless, sale_stock_picking_note is not yet migrated into 12.0

2019-09-19 16:45 UTC, rousseldenis approved these changes
LGTM. Code review

2019-09-20 10:43 UTC, lmignon commented
/ocabot merge patch

2019-09-20 11:21 UTC, merged