[12.0][MIG] base_url
shopinvader/odoo-shopinvader pull request #318
Opened 2019-05-10 17:07 UTC by rousseldenis

2019-05-10 18:13 UTC, rvalyi requested changes
There should be an adicional line break in the README.rst after "This module helps to manage url with these features:" for the proper RST display of the items listed next.

2019-05-13 13:44 UTC, rousseldenis commented
@rvalyi Done.

Travis green!

2019-05-14 07:41 UTC, lmignon commented on base_url/tests/models_mixin.py
> +                if isinstance(parents, (str, bytes))
parents should never be bytes...

2019-05-14 09:24 UTC, acsonefho approved these changes
LGTM (about code)

2019-05-16 07:08 UTC, lmignon approved these changes

2019-05-16 07:08 UTC, merged