WIP [10.0][ADD] Add wizard to bind shopinvader.partner
shopinvader/odoo-shopinvader pull request #323
Opened 2019-05-15 10:32 UTC by acsonefho

Add a wizard to bind selected partners.
The wizard is quite similar to the one used to bind partners on the portal.

Todo:
Unit test

2019-05-16 07:17 UTC, lmignon commented
@acsonefho What's the purpose of this PR? If you bind a partner to backend, you should also create an account into locomotive. (And remove / deactivate the account when you unbind...)

2019-05-16 08:11 UTC, acsonefho commented
> @acsonefho What's the purpose of this PR? If you bind a partner to backend, you should also create an account into locomotive. (And remove / deactivate the account when you unbind...)

@lmignon The purpose of this PR is only to bind existing partners to a shopinvader backend. About the creation of locomotive account, it's automatically done (if the module shopinvader_locomotive is installed of course). Currently the unbind is not implemented.

2019-05-20 08:35 UTC, lmignon requested changes

2019-05-20 08:35 UTC, lmignon commented on shopinvader/wizards/shopinvader_partner_binding_line.py
> +        for record in self.filtered(lambda r: r.bind):
@acsonefho WE must raise a UserError if bind is unticked since this functionality is not implemented.

2019-09-17 12:58 UTC, Cedric-Pigeon requested changes

2019-09-17 12:58 UTC, Cedric-Pigeon commented on shopinvader/wizards/shopinvader_partner_binding.xml
> +                name="Shopinvader partner binding"
"Bind to a website" would be better...

2019-09-19 14:11 UTC, lmignon approved these changes

2019-09-19 14:12 UTC, lmignon commented
/ocabot merge patch

2019-09-19 15:38 UTC, merged