[12.0] Add shopinvader_partner_firstname
shopinvader/odoo-shopinvader pull request #475
Opened 2019-10-24 11:47 UTC by simahawk

Integrates `partner_firstname`.

Temporarely includes #469 and #471 because of some common changes.

2019-10-24 12:02 UTC, lmignon reviewed
At first read, LGTM

2019-11-05 15:16 UTC, simahawk commented
rebased on #469 as it contains a fix for master and to be merged soon

2019-11-05 16:57 UTC, simahawk commented
test to fix https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/607689374#L3457

2019-11-06 10:14 UTC, simahawk commented
@lmignon good for you?

2019-11-07 08:31 UTC, simahawk commented
hmm I don't get why tests fail only in one of the jobs https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/608155216?utm_medium=notification&utm_source=github_status

2019-11-13 12:14 UTC, simahawk commented
@lmignon @sebastienbeau can you give me your opinion regarding this? 
https://github.com/shopinvader/odoo-shopinvader/pull/475/commits/6196b937437b9efd8503a1a45da9c2c50d2748c9
To me it seems more complete and it fixes the case whereas the cache does not contain one of the values.

2019-11-13 14:36 UTC, lmignon commented on shopinvader/models/shopinvader_partner.py
> +                partner[key]  # load missing key
:champagne:

2019-11-13 16:31 UTC, simahawk commented
last build issues fixed, we can merge as it gets green.

2019-11-14 14:10 UTC, simahawk commented
LINT tests seem to have some warnings for many modules but not for mine. I think we can safely merge and then

2019-11-14 16:28 UTC, lmignon requested changes

2019-11-14 16:28 UTC, lmignon commented on shopinvader/models/shopinvader_partner.py
> +                partner[key]  # load missing key
```suggestion
                # pylint: disable=pointless-statement
                partner[key]  # load missing key
```
@simahawk IMO pylint is failing due to this line https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/611453281#L355
![image](https://user-images.githubusercontent.com/544090/68875291-e1551500-0702-11ea-8081-bd6b770570a0.png)

2019-11-14 16:28 UTC, lmignon commented on shopinvader/models/shopinvader_partner.py
> +            if key not in partner._cache:
@simahawk We don't have to check if the key is already into the cache... it's done by the orm
https://github.com/odoo/odoo/blob/12.0/odoo/fields.py#L989

2019-11-15 10:36 UTC, simahawk commented
all :green_heart: finally :)

2019-11-15 10:37 UTC, simahawk commented
/ocabot merge patch

2019-11-15 11:04 UTC, merged

2019-11-15 11:06 UTC, lmignon commented
:champagne: