[12.0][REF] Make search engine locomotive export settings generic
shopinvader/odoo-shopinvader pull request #477
Opened 2019-10-28 13:02 UTC by simahawk

**Implements:** https://github.com/shopinvader/odoo-shopinvader/issues/466
**Requires:** https://github.com/OCA/search-engine/pull/35
**Causes:** https://github.com/shopinvader/odoo-shopinvader-payment/pull/15

2019-10-28 17:39 UTC, lmignon requested changes
@simahawk IMO OCA/search-engine#35 should not be required. `_search_engine_name`could be defined as a simple computed fields.Char on  `se.backend.spec.abstract`:

```python
search_engine_name = fields.Char(compute="_compute_search_engine_name")

@api.depends("specific_model")
def _compute_search_engine_name(self):
    for rec in self:
        rec._search_engine_name = rec._specific_model.split(".")[-1]

```

Since this field will only be used by shopinvader (at least for the moment) it should be declared ont shopinvader_search_engine.

What do you think about?

2019-10-28 18:38 UTC, simahawk commented
@lmignon I thought about it but I don't like it because it's not explicit and potentially you can have whatever string at the end of the model name. However, if you prefer it like this, no problem :)

2019-10-29 09:09 UTC, lmignon commented
@simahawk My concern is that this new class attribute is somehow redundant with the model name. I understand the need to be able to say "this is XYZ search engine".  But IMO, we already have 2 places where this needs is already covered. The attribute `_name` of the specialized backend and the field `specific_model` on "se.backend".

You're right to prefer explicit over implicit to implement this UC. So I'll not block since at this stage it's a matter of feeling. 

If it's ok for you, I'll merge https://github.com/OCA/search-engine/pull/35

2019-10-29 09:42 UTC, simahawk commented
@lmignon the good thing is that the attribute name comes from a property -> we can convert it to a field if we think it's better. It won't change current implementation -> let's merge it and improve later, fine?

2019-10-29 10:08 UTC, lmignon commented
It's fine for me..

2019-10-29 10:08 UTC, lmignon approved these changes

2019-10-29 10:12 UTC, lmignon commented
@simahawk Can you fix flake8 PLZ...

2019-10-29 10:22 UTC, rousseldenis commented on shopinvader_locomotive/component/shopinvader_site_export_mapper.py
> +        index_product = se_backend.index_ids.filtered(
Prefer using :

```suggestion
        from odoo.fields import first
        index_product = first(se_backend.index_ids.filtered(
```
so you can remove 
``` 
index_product = index_product[0]
```

2019-10-29 11:09 UTC, simahawk commented
Linting fixed. 2 builds are failing tho but they same unrelated:

https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/603896021
https://travis-ci.org/shopinvader/odoo-shopinvader/jobs/603896022

Seems there's lack of permissions somewhere. Do they ring any bell to you?

2019-10-29 15:47 UTC, simahawk commented
hmm might be related to the change in the base class for tests. Debugging in WIP

2019-10-30 11:41 UTC, simahawk commented
I finally found the reason for test failure: bad isolation between demo data for tests. `shopinvader_elasticsearch` adds a SE to base demo backend which cause SE settings to be included into basic site export.
Should be green now.

2019-10-30 13:25 UTC, simahawk commented
![external-content duckduckgo com](https://user-images.githubusercontent.com/347149/67861730-179a6e00-fb21-11e9-90b7-44c6ccb81e2d.gif)

2019-10-30 16:23 UTC, simahawk commented
@lmignon finally greeen :)
I guess I can try my new super powers now! (thanks, BTW :wink: )

2019-10-30 16:23 UTC, simahawk commented
/ocabot merge minor

2019-10-30 17:31 UTC, merged