[10.0][IMP] Use the technical user to recompute and export
shopinvader/odoo-shopinvader pull request #515
Opened 2019-11-18 08:29 UTC by acsonefho

On the shopinvader backend view, you have buttons to "Recompute" and "Export".

Edit the current behavior to use the technical user (only if it set on the current user's company).
Because currently, if a user click on this button, he can't switch his company until the end of each jobs (it will cause Access rights exception).

As the technical user not required (on the company) and to keep compatibility: no error will be raised if no technical user (it will use the current user, as currently).

2019-11-18 08:48 UTC, Cedric-Pigeon requested changes
Could you please add a test?

2019-11-18 09:47 UTC, acsonefho commented
> Could you please add a test?

Done :)

2019-11-18 09:50 UTC, Cedric-Pigeon approved these changes
Code review

2019-12-10 16:33 UTC, lmignon reviewed
@acsonefho I would avoid a new dependency for shopinvader_search_engine....

2019-12-12 13:17 UTC, Cedric-Pigeon commented
@lmignon I am vacillating about your comment. On one hand, I agree we must limit as must as possible dependencies but on the other hand, this is the only way to trust the behaviour in a multi-company context.
The problem is if a user clicks on recompute and changes companies, he is not aware of the failing jobs...

2020-03-27 17:31 UTC, sebastienbeau reviewed
I am ok for adding this new dependency.
For me the base_technical_user should be in the core to solve all multi-company issue.

Regarding the implementation, maybe it will be smarted to add some helper on base_technical_user ?
What do you think about moving the logic of _use_technical_user_if_set in base_technical_user?

Maybe something like (with a better naming) we can inherit the BaseModel class of odoo

```
def sudo_tech(raise_if_missing=False):
    self_sudoer = self
    tech_user = self.env.user.company_id.user_tech_id
    if tech_user:
        self_sudoer = self.sudo(tech_user.id)
    elif raise_if_missing:
        raise UserError("The technical user is missing in the company {}".format(self.env.user.company_id.name))
    return self_sudoer
```

Then you can use it everywhere with 

```
self.sudo_tech().mapped("se_backend_id.index_ids").force_recompute_all_binding()
```

What do you think ?
@Cedric-Pigeon @lmignon

2020-03-30 05:35 UTC, Cedric-Pigeon commented
@acsonefho @sebastienbeau's idea is really good and will simplify a lot of pieces of code. Can you proceed?

2020-03-31 12:27 UTC, acsonefho commented
> @acsonefho @sebastienbeau's idea is really good and will simplify a lot of pieces of code. Can you proceed?

Ok, I plan to do it in few days

2020-04-24 12:59 UTC, sebastienbeau commented
I have done a PR in server-tools https://github.com/OCA/server-tools/pull/1824

2020-04-24 17:11 UTC, sebastienbeau commented
PR is merge I am going to modify the PR and merge it

2020-04-24 17:18 UTC, sebastienbeau commented
Replaced by : https://github.com/shopinvader/odoo-shopinvader/pull/622

2020-04-24 22:49 UTC, merged