[10.0][FIX] shopinvader.partner force email in lower case
shopinvader/odoo-shopinvader pull request #529
Opened 2019-12-06 06:59 UTC by acsonefho

**Current issue:**
When an email is in upper case, we have a traceback related to the locomotive API during the manual binding (using dedicated wizard).

**How to reproduce:**
- Ensure your shopinvader backend is correctly linked to a locomotive;
- Go on a partner form view (not already binded to a backend);
- Put the email in upper case;
- Use the binding wizard;
- Booom!

**Fix:**
Just force the partner's email in lower case in case of binding.
Don't need a migration script (for existing binding) because if the email was in upper case, there is no binding due to this bug. So nothing to fix.

2019-12-06 07:13 UTC, simahawk requested changes

2019-12-06 07:13 UTC, simahawk commented on shopinvader/tests/test_shopinvader_partner_binding.py
> +        # This partner shouldn't be already binded
```suggestion
        # This partner shouldn't be already bound
```

2019-12-06 07:13 UTC, simahawk commented on shopinvader/tests/test_shopinvader_partner_binding.py
> +        return
```suggestion
```

2019-12-06 07:13 UTC, simahawk commented on shopinvader/wizards/shopinvader_partner_binding_line.py
> +                    record.partner_id.write({"email": email_lower})
I'd disable tracking
```suggestion
                    record.partner_id.with_context(tracking_disable=True).write({"email": email_lower})
```

2019-12-06 07:13 UTC, simahawk commented on shopinvader/wizards/shopinvader_partner_binding_line.py
> +                    record.partner_id.write({"email": email_lower})
as you are writing again here, just define a dict of values and inject the email if needed

2019-12-06 07:28 UTC, simahawk approved these changes

2019-12-06 07:33 UTC, acsonefho commented
@simahawk Thanks for your review and improvements :)

2019-12-12 06:22 UTC, Cedric-Pigeon approved these changes

2019-12-12 07:05 UTC, simahawk commented
/ocabot merge patch

2019-12-12 07:46 UTC, merged