[10.0][FIX] shopinvader_promotion_rule fix promotions applied
shopinvader/odoo-shopinvader pull request #562
Opened 2020-01-24 15:06 UTC by acsonefho

When the function `write_with_onchange(...)` is called, promotions are completely ignored (so prices doesn't include discounts etc).
It's an issue when an anonymous user create an account and the fiscal position is updated (so when `reset_price_tax()` is called (cfr shopinvader module)).

So the fix is just to call the apply_promotions() when we call `reset_price_tax()`.

2020-01-24 15:48 UTC, lmignon requested changes

2020-01-24 15:48 UTC, lmignon commented on shopinvader_promotion_rule/models/sale_order.py
> +        self.apply_promotions()
@acsonefho IMO You must check if the SO has promotion rules before calling the apply_promotions.

2020-01-30 10:47 UTC, Cedric-Pigeon approved these changes

2020-02-11 10:36 UTC, rousseldenis approved these changes
Code review

2020-02-11 10:36 UTC, rousseldenis commented
@lmignon Could you update your review ?

2020-02-11 10:38 UTC, lmignon commented
/ocabot merge patch

2020-02-11 10:38 UTC, lmignon approved these changes

2020-02-11 11:26 UTC, merged