[10.0][ADD] Add module shopinvader_product_stock_assortment.
shopinvader/odoo-shopinvader pull request #567
Opened 2020-02-04 09:09 UTC by acsonefho

This glue module is used between `shopinvader_assortment` and `shopinvader_product_stock` modules to let the assortment use stock info (warehouse) to evaluate the domain.

Otherwise it should have some inconsistency when the assortment is evaluated and data/json exported (as the export use warehouses set on the backend)

2020-02-04 09:37 UTC, simahawk requested changes
Question: judging from the test, this module blocks the creation of bindings for products that are out of stock. Is this correct?

2020-02-04 09:37 UTC, simahawk commented on shopinvader_product_stock_assortment/__manifest__.py
> +    "version": "10.0.1.0.1",
1.0.0 ?

2020-02-04 09:37 UTC, simahawk commented on shopinvader_product_stock_assortment/__manifest__.py
> +    "website": "https://shopinvader.com",
https://github.com/shopinvader/odoo-shopinvader

2020-02-04 09:37 UTC, simahawk commented on shopinvader_product_stock_assortment/tests/test_product_auto_bind.py
> +    def setUp(self):
please use a SavepointCase and replace setUp w/ setUpClass

2020-02-04 09:43 UTC, acsonefho commented
> Question: judging from the test, this module blocks the creation of bindings for products that are out of stock. Is this correct?

@simahawk It depends on the assortment filter. If you set a domain `[('qty_available', '>', 0)]`, yes these products with `qty_available <= 0` won't be binded.
(And thanks for your review!)

2020-02-06 12:52 UTC, Cedric-Pigeon approved these changes

2020-03-18 12:39 UTC, Cedric-Pigeon commented
@simahawk is this one correct for you?

2020-03-18 13:13 UTC, simahawk approved these changes

2020-03-18 13:37 UTC, Cedric-Pigeon commented
/ocabot merge patch

2020-03-19 08:16 UTC, Cedric-Pigeon commented
/ocabot merge patch

2020-03-19 16:59 UTC, sebastienbeau approved these changes
LGTM

2020-03-20 06:29 UTC, Cedric-Pigeon commented
/ocabot merge patch

2020-03-20 13:06 UTC, merged