[10.0][IMP][ADD] shopinvader - Document generate/download (pdf)
shopinvader/odoo-shopinvader pull request #570
Opened 2020-02-05 14:48 UTC by acsonefho

Add possibility to download the sale order (pdf).
As the behavior is similar to invoice, it's better to extract the code and re-use it.

- Extract the download part of invoice service;
- Create an abstract component;
- Apply it on invoice service;
- Apply it on sale service;
- Extract tests about download (and make a new class);
- Apply this test class on invoice + sale tests.

2020-02-06 07:26 UTC, simahawk approved these changes
very nice :)
Do you plan to move it to v12 as well?

2020-02-06 07:26 UTC, simahawk commented on shopinvader/services/abstract_download.py
> +    def _get_report_action(self, target):
I'd pass `params` here to be able to control the action on demand.
Not a blocker tho,

2020-02-06 08:04 UTC, acsonefho commented
> very nice :)
> Do you plan to move it to v12 as well?

Yes but I prefer to wait and see the usage in production and improve if necessary.
Then migrate in v12.0 in one shot.

2020-02-06 10:21 UTC, lmignon requested changes
A little change required.... nevertheless it's a nice improvement!

2020-02-06 10:21 UTC, lmignon commented on shopinvader/services/abstract_download.py
> +        headers, content = self._get_binary_content(target)
@acsonefho you should mast params to all the methods defined into this abstract...

2020-02-07 07:07 UTC, lmignon requested changes

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/abstract_download.py
> +    def _get_binary_content(self, target, params=False):
@acsonefho `params=None`

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/abstract_download.py
> +    def _get_report(self, report_name, report_type, params=False):
@acsonefho `params=None`

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/abstract_download.py
> +        self, target, report, format, params=False
@acsonefho `params=None`

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/invoice.py
> +    def _get_report_action(self, target, params=False):
@acsonefho `params=None`

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/abstract_download.py
> +    def _get_report_action(self, target, params=False):
@acsonefho `params=None`

2020-02-07 07:07 UTC, lmignon commented on shopinvader/services/sale.py
> +    def _get_report_action(self, target, params=False):
@acsonefho `params=None`

2020-02-07 09:28 UTC, lmignon approved these changes

2020-02-07 09:28 UTC, lmignon commented
@acsonefho Can you check pre-commit

2020-02-07 09:33 UTC, lmignon commented
@acsonefho pre-commit fixed..

2020-02-12 14:38 UTC, rousseldenis approved these changes
Great!

2020-03-19 08:10 UTC, Cedric-Pigeon commented
/ocabot merge patch

2020-03-19 14:02 UTC, merged