[10.0] add new addon to allow to display the category image if the product does not have one
shopinvader/odoo-shopinvader pull request #572
Opened 2020-02-06 11:05 UTC by Cedric-Pigeon

2020-02-07 07:01 UTC, simahawk requested changes

2020-02-07 07:01 UTC, simahawk commented on shopinvader_category_image_for_product/__manifest__.py
> +    "website": "http://www.shopinvader.com",
https://github.com/shopinvader/odoo-shopinvader

2020-02-07 07:01 UTC, simahawk commented on shopinvader_category_image_for_product/models/shopinvader_variant.py
> +            category = record.shopinvader_categ_ids.filtered(
can you split this to `_get_category_by_backend`? or similar?

2020-02-07 07:01 UTC, simahawk commented on shopinvader_category_image_for_product/readme/DESCRIPTION.rst
> +This paddon allows to display the category image on a product without images
```suggestion
This addon allows to display the category image when a product has no images.
```

2020-02-12 14:33 UTC, rousseldenis approved these changes
Code review

2020-03-18 14:20 UTC, Cedric-Pigeon commented
@simahawk Are you still waiting something from me on this one?

2020-03-19 10:46 UTC, simahawk approved these changes

2020-03-19 10:48 UTC, rousseldenis commented
/ocabot merge

2020-03-19 17:03 UTC, sebastienbeau approved these changes

2020-03-20 06:19 UTC, Cedric-Pigeon commented
/ocabot merge

2020-03-20 06:56 UTC, merged