12.0 wip product_stock_state
shopinvader/odoo-shopinvader pull request #573
Opened 2020-02-06 13:20 UTC by kevinkhao

2020-02-10 13:32 UTC, sebastienbeau requested changes
Travis is red please fix it

2020-02-10 13:32 UTC, sebastienbeau commented on product_stock_state/views/res_config_settings_view.xml
> +                            qqqqqqqqqqqqqqqqqqqqqqqqqqqqq
need cleanup

2020-02-10 13:32 UTC, sebastienbeau commented on product_stock_state/views/res_config_settings_view.xml
> +        <!--<div id="production_lot_info" position="after">-->
need cleanup

2020-02-11 07:56 UTC, rousseldenis commented
@sebastienbeau Even if we have easier access to this repo, I suggest to move those generic modules like 'product_...' in ... the OCA product repository as it can fullfill other users requirements and could be maintained by those others too.

2020-02-13 11:11 UTC, sebastienbeau commented
@rousseldenis good idea !
@kevinkhao can you do a PR here : https://github.com/OCA/product-attribute ?
Thanks

2020-02-26 08:57 UTC, kevinkhao commented
sure @sebastienbeau https://github.com/OCA/product-attribute/pull/575

2020-03-13 14:17 UTC, PierrickBrun commented
I think we should close this PR

2020-03-18 16:24 UTC, hparfr commented
Merged, new home for this module will be OCA/product-attribute#575

2020-03-18 16:24 UTC, closed without merging