PORT base_url
shopinvader/odoo-shopinvader pull request #61
Opened 2017-10-02 10:16 UTC by bealdav

Note:
In v10 methods which inherits of models.Model have `api.multi` default behavior (see last odoo days @ antonylesuisse) so I remove them and attach `api.model` to other methods.

2017-10-02 12:07 UTC, hparfr requested changes

2017-10-02 12:07 UTC, hparfr commented on base_url/models/base_url.py
>          return slugify(self.record_id.with_context(
Todo : refactor it.  record_id may exist or not. May be @api.somethingelse

2017-10-02 13:48 UTC, bealdav commented
ping @hparfr fixed

2017-10-02 13:52 UTC, legalsylvain commented
Hi @bealdav thanks ! 
2 things : could you 
-  split .py file to have one file per model ? 
- improve / fix manifest file. (not OCA module for instance, and description is quite poor).

regards.

2017-10-02 15:19 UTC, hparfr approved these changes

2017-10-02 20:02 UTC, merged

2017-10-03 02:43 UTC, legalsylvain commented on base_url/__manifest__.py
>      # any module necessary for this one to work correctly
should not depend on base ?

2017-10-03 06:39 UTC, bealdav commented on base_url/__manifest__.py
>      # any module necessary for this one to work correctly
good catch, fixed in v10. Thanks