[10.0][IMP] shopinvader_delivery_carrier: Adds carrier descriptions
shopinvader/odoo-shopinvader pull request #628
Opened 2020-05-04 16:10 UTC by rousseldenis

Adds description, description_sale and description_picking in
delivery service in order to enhance customer UX.

2020-05-04 16:10 UTC, rousseldenis commented
@Cedric-Pigeon

2020-05-05 05:29 UTC, Cedric-Pigeon requested changes

2020-05-05 05:29 UTC, Cedric-Pigeon commented on shopinvader_delivery_carrier/tests/__init__.py
> +# from . import test_carrier
@rousseldenis is it expected?

2020-05-05 06:07 UTC, rousseldenis commented on shopinvader_delivery_carrier/tests/__init__.py
> +# from . import test_carrier
Nope indeed !

2020-05-08 15:33 UTC, sebastienbeau commented
Hum, I just not sure that it make seen to export so much field
- description_picking is normally use for "stockable" product in order to have a specific name in the delivery
- description is for internal purpose
- description_sale is use on sale order

So maybe just exporting description_sale and map it to description (in the API) is maybe enough?

I fear that front dev ask us too much question "what the fucking hell you have 3 descriptions? which is the good one?"

What do you think?

2020-05-08 16:18 UTC, rousseldenis commented
@Cedric-Pigeon An advice on this ?

2021-03-26 10:36 UTC, sebastienbeau commented
@rousseldenis @Cedric-Pigeon still valid?

2022-02-07 07:37 UTC, lmignon commented
Closing since 10.0 is no more actively maintained.

2022-02-07 07:37 UTC, closed without merging