[10.0][ADD] Add shopinvader_membership
shopinvader/odoo-shopinvader pull request #631
Opened 2020-05-06 11:34 UTC by baimont

This addon adds services to access a customer's membership lines.

2020-05-07 06:15 UTC, simahawk requested changes

2020-05-07 06:15 UTC, simahawk commented on shopinvader_membership/services/membership.py
> +        # _description_selection return a list of tuple (str, str).
use converto_to_export ;)
See https://github.com/shopinvader/odoo-shopinvader/blob/12.0/shopinvader/models/res_partner.py#L131

2020-05-07 06:15 UTC, simahawk commented on shopinvader_membership/services/membership.py
> +            {"state": self._get_selection_label(membership_line, "state")}
I'd return `{"state": {"value": ..., "label": ...}}`

2020-05-07 06:15 UTC, simahawk commented on shopinvader_membership/tests/test_membership_service.py
> +        self.product = self.product_obj.create(
Please move all statements but the service init to setUpClass as they will run only once.

2020-05-08 14:39 UTC, sebastienbeau commented
@PierrickBrun I think it will interest you !

2020-05-08 18:39 UTC, PierrickBrun commented
Great ! @hparfr

2020-05-12 09:25 UTC, baimont commented
Thanks for your review @simahawk 
I made a few changes

2020-05-12 18:50 UTC, simahawk approved these changes

2020-05-14 13:44 UTC, Cedric-Pigeon approved these changes

2020-05-18 09:19 UTC, rousseldenis commented
@baimont Could you rebase?

2020-05-26 12:51 UTC, rousseldenis commented
/ocabot merge patch

2020-05-26 13:22 UTC, merged