[13.0][PORT] #596 from 10.0: being able to make the difference between an update done by the customer and update done internally in Odoo
shopinvader/odoo-shopinvader pull request #667
Opened 2020-05-26 12:51 UTC by HviorForgeFlow

Port #596 from 10.0 to 13.0

2020-06-19 16:54 UTC, sebastienbeau commented
@HviorForgeFlow  can you check why the bot is failling?

2020-06-19 19:15 UTC, simahawk requested changes

2020-06-19 19:15 UTC, simahawk commented on shopinvader/tests/test_cart.py
> +        time.sleep(1)
these sleeps on every test, please use another approach like freezegun

2020-11-20 13:39 UTC, rousseldenis commented
@HviorForgeFlow

2022-04-08 15:15 UTC, rousseldenis commented
@HviorForgeFlow Could you rebase ?

2023-08-27 12:14 UTC, closed without merging