[13.0][PORT] 661 from 12.0
shopinvader/odoo-shopinvader pull request #689
Opened 2020-05-29 15:01 UTC by sebastienbeau

Port #661 from 12.0 to 13.0.

2020-06-11 16:17 UTC, simahawk requested changes

2020-06-11 16:17 UTC, simahawk commented on shopinvader/data/ir_cron.xml
> +        <field name="code">model._launch_sale_price_update()</field>
```suggestion
        <field name="state">code</field>
        <field name="code">model._launch_sale_price_update()</field>
```

2020-06-11 16:17 UTC, simahawk commented on shopinvader/models/sale.py
> +        """
```suggestion
        """Update prices on current sale orders.

        Behavior:

        * Update the pricelist with the one set on the backend;
           => If no pricelist, use the default define on the partner.
        * Then launch the price update (module sale_order_price_recalculation).

        :return: bool
        """
```

2020-06-11 16:17 UTC, simahawk commented on shopinvader/models/shopinvader_backend.py
> +    @api.multi
multi is gone

2020-06-11 16:17 UTC, simahawk commented on shopinvader/tests/test_sale.py
> +        self.sale = sale = self.env["sale.order"].create(
you should return `sale` instead of setting it on the instance

2020-06-11 16:17 UTC, simahawk commented on shopinvader/tests/test_sale.py
> +        self.second_pricelist = self.env["product.pricelist"].create(
return the pricelist instead

2020-06-11 16:20 UTC, simahawk commented
duplicate of https://github.com/shopinvader/odoo-shopinvader/pull/679 ?
CC @rousseldenis

2020-06-12 07:29 UTC, rousseldenis commented
> duplicate of #679 ?
> CC @rousseldenis

Indeed and depending on a long debate https://github.com/OCA/sale-workflow/pull/1155

About how to trigger onchanges. Form() that I don't like or onchange_helper

2020-06-19 16:46 UTC, sebastienbeau commented
I am closing this PR as it a duplicated sorry

2020-06-19 16:46 UTC, closed without merging