[10.0][IMP] shopinvader_guest_mode: Allow to bind a guest to real
shopinvader/odoo-shopinvader pull request #712
Opened 2020-07-03 15:52 UTC by rousseldenis

2020-07-03 16:07 UTC, Cedric-Pigeon requested changes

2020-07-03 16:07 UTC, Cedric-Pigeon commented on shopinvader_guest_mode/wizards/partner_binding_line.py
> +                partner_binding.write({"is_guest": False})
you should also reset `expiry_dt`

2020-07-03 16:08 UTC, Cedric-Pigeon commented on shopinvader_guest_mode/wizards/partner_binding_line.py
> +                partner_binding.write({"is_guest": False})
well, sorry missed it is a computed field

2020-07-06 07:40 UTC, rousseldenis commented
@Cedric-Pigeon Could you update your review?

2020-07-06 08:06 UTC, Cedric-Pigeon approved these changes
Code review and functional tests

2021-03-26 14:54 UTC, hparfr approved these changes

2021-03-26 14:56 UTC, hparfr commented
/ocabot merge minor

2021-03-26 15:16 UTC, hparfr commented
Pre-commit is failing

2021-03-26 15:44 UTC, rousseldenis commented
> Pre-commit is failing

I'll rebase

2021-03-26 17:20 UTC, hparfr commented
/ocabot merge minor

2021-03-26 18:07 UTC, merged