[10.0][IMP] shopinvader_promotion_rule: let possibility to disable promotion rule by backend
shopinvader/odoo-shopinvader pull request #724
Opened 2020-07-31 13:17 UTC by acsonefho

Add a boolean on the backend to set if promotion rules should be applied or not.
The unit test only check the specific behavior.
The goal is not to test full `sale_promotion_rule` module.

2020-07-31 13:41 UTC, rousseldenis requested changes
LGTM. Minor remarks

2020-07-31 13:41 UTC, rousseldenis commented on shopinvader_promotion_rule/models/shopinvader_backend.py
> +        default=False,
Remove this, default.

2020-07-31 13:41 UTC, rousseldenis commented on shopinvader_promotion_rule/models/shopinvader_backend.py
> +        help="Set to True to disable promotion rules for this backend",
```suggestion
        help="Check this to disable promotion rules for this backend",
```

Set to True is too technical

2020-07-31 14:51 UTC, lmignon approved these changes
LGTM once comments from @rousseldenis are taken into account

2020-08-25 11:29 UTC, rousseldenis approved these changes
Code review

2021-03-11 15:40 UTC, Cedric-Pigeon commented
/ocabot merge minor

2021-03-11 16:10 UTC, merged