[MIG] 14.0 algolia
shopinvader/odoo-shopinvader pull request #856
Opened 2021-01-27 14:17 UTC by PierrickBrun

based on #855

2021-02-19 14:11 UTC, acsonefho approved these changes
Code LGTM

2021-03-26 12:50 UTC, Cedric-Pigeon approved these changes

2021-03-26 13:57 UTC, kevinkhao commented
dependencies seem OK @Cedric-Pigeon

2021-03-26 13:59 UTC, rousseldenis commented
> dependencies seem OK @Cedric-Pigeon

Still needs connector_algolia

2021-03-26 14:03 UTC, rousseldenis commented
> > dependencies seem OK @Cedric-Pigeon
> 
> Still needs connector_algolia

@PierrickBrun I think you did not create PR for you 14.0-shopinvader there https://github.com/OCA/search-engine/pulls

2021-03-26 14:10 UTC, PierrickBrun commented
> > > dependencies seem OK @Cedric-Pigeon
> > 
> > 
> > Still needs connector_algolia
> 
> @PierrickBrun I think you did not create PR for your 14.0-shopinvader there https://github.com/OCA/search-engine/pulls

I will update https://github.com/OCA/search-engine/pull/67 when https://github.com/OCA/search-engine/pull/73 is merged. I created 14.0-shopinvader to be able to run the CI, but did not intend to merge it

2021-03-26 14:36 UTC, mourad-ehm approved these changes

2021-05-21 11:34 UTC, simahawk commented
NOTE: to be rebase and test against https://github.com/OCA/search-engine/pull/86 (needs review)
All other PRs have been merged.

2021-05-21 11:34 UTC, simahawk requested changes
just to prevent accidental merge ;)

2021-06-15 08:01 UTC, simahawk commented
@PierrickBrun can you rebase/cleanup/etc?

2021-06-15 09:40 UTC, PierrickBrun commented
> @PierrickBrun can you rebase/cleanup/etc?

@simahawk  done

2021-06-17 09:12 UTC, simahawk approved these changes
@PierrickBrun one small thing to change: move test dep to test-dependencies.txt

2021-06-17 09:12 UTC, simahawk commented on shopinvader_algolia/__manifest__.py
>      "external_dependencies": {"python": ["vcrpy_unittest"]},
this a dep only for tests, can you remove it?

2021-07-07 20:08 UTC, sebastienbeau approved these changes
/ocabot merge nobump

2021-07-08 08:32 UTC, PierrickBrun commented
/ocabot merge nobump

2021-07-08 08:46 UTC, merged