[MIG] 14.0 product stock state
shopinvader/odoo-shopinvader pull request #860
Opened 2021-01-27 16:04 UTC by PierrickBrun

2021-03-26 12:49 UTC, Cedric-Pigeon approved these changes

2021-05-11 14:25 UTC, david-popa commented on test-requirements.txt
> +odoo14-addon-product_stock_state @ git+https://github.com/OCA/product-attribute.git@refs/pull/715/head#subdirectory=setup/product_stock_state
product_stock_state has been merged so this line (commit) should be removed

2021-05-24 12:37 UTC, simahawk requested changes
TODO: rebase and cleanup test requirements

2021-05-25 06:34 UTC, simahawk commented
Done on https://github.com/shopinvader/odoo-shopinvader/pull/976 to speed it up.

2021-05-25 06:34 UTC, closed without merging