[MIG] shopinvader_assortment: Migration to 14.0
shopinvader/odoo-shopinvader pull request #863
Opened 2021-01-28 10:24 UTC by chafique-delli

2021-02-19 14:52 UTC, acsonefho approved these changes
Code LGTM

2021-03-26 12:47 UTC, Cedric-Pigeon approved these changes
Code review

2021-03-26 12:49 UTC, Cedric-Pigeon commented
/ocabot merge nobump

2021-05-24 12:35 UTC, simahawk requested changes

2021-05-24 12:35 UTC, simahawk commented on oca_dependencies.txt
> +server-tools
this is not needed

2021-05-24 12:35 UTC, simahawk commented on shopinvader_assortment/models/shopinvader_backend.py
> +        variants_binded = shopinvader_variant_obj.search([("backend_id", "=", self.id)])
s/binded/bound

2021-05-24 12:35 UTC, simahawk commented on test-requirements.txt
> -
this file must be cleaned up

2021-05-24 12:36 UTC, simahawk commented
please remove the last merge commit as well :pray:

2021-05-25 05:45 UTC, simahawk commented
Replaced by #973

Sorry guys, is getting insane w/ pending merges :sweat_smile: and I kind of need to move faster :wink: 

I've done what commented on #863 to clean up.

2021-05-25 05:45 UTC, closed without merging