[MIG] shopinvader_wishlist: Migration to 14.0
shopinvader/odoo-shopinvader pull request #867
Opened 2021-01-28 13:55 UTC by chafique-delli

2021-02-19 14:41 UTC, acsonefho approved these changes
Code LGTM

2021-03-26 16:04 UTC, rousseldenis commented
@chafique-delli Could you put on your PR description when it depends on a non migrated module (with the PR link) ? It's easier for reviewers. Thanks

2021-05-24 12:24 UTC, simahawk requested changes

2021-05-24 12:24 UTC, simahawk commented on oca_dependencies.txt
> +sale-workflow
we don't need this we use MQT=PIP

2021-05-24 12:24 UTC, simahawk commented on shopinvader_wishlist/models/product_set.py
> +        # Backward compat
this should be dropped

2021-05-24 12:24 UTC, simahawk commented on shopinvader_wishlist/services/wishlist.py
> +    def add_items_to_cart(self, _id, **params):
there are other changes to include

2021-05-24 12:25 UTC, simahawk commented
I opened https://github.com/shopinvader/odoo-shopinvader/pull/972 to include all recent fix/imp and remove deprecated code which requires #970

2021-05-24 12:25 UTC, closed without merging