[MIG] shopinvader_locomotive_wishlist: Migration to 14.0
shopinvader/odoo-shopinvader pull request #869
Opened 2021-01-29 11:04 UTC by chafique-delli

2021-02-19 14:37 UTC, acsonefho approved these changes
Code LGTM

2021-03-26 13:20 UTC, rousseldenis commented
@chafique-delli Could you rebase ?

2021-05-24 12:39 UTC, simahawk requested changes
please include this very important fix from v13 https://github.com/shopinvader/odoo-shopinvader/commit/4f4d4e6fdf43aa5b3688cf6db7fb024c6b9c1a23

2021-05-24 12:39 UTC, simahawk commented on oca_dependencies.txt
> +sale-workflow
not needed

2021-05-24 12:39 UTC, simahawk commented on test-requirements.txt
> +
drop these changes

2021-05-25 06:21 UTC, simahawk commented
Replaced by #975 

Sorry guys, is getting insane w/ pending merges sweat_smile and I kind of need to move faster wink

I've included the fix from v13 mentioned above.

2021-05-25 06:21 UTC, closed without merging