[14.0][MIG] shopinvader_sale_packaging
shopinvader/odoo-shopinvader pull request #873
Opened 2021-02-01 09:02 UTC by hparfr

2021-02-01 09:28 UTC, PierrickBrun approved these changes
Do not merge until test-requirements PRs are merged

2021-02-19 14:03 UTC, acsonefho approved these changes
Code LGTM

2021-02-19 14:03 UTC, acsonefho commented on shopinvader_sale_packaging/services/abstract_sale.py
> +                    "packaging": line.product_packaging.jsonify(["id", "name"])[0],
**Tips:** you can use the `one=True` parameter
https://github.com/OCA/server-tools/blob/14.0/base_jsonify/models/models.py#L93

```suggestion
                    "packaging": line.product_packaging.jsonify(["id", "name"], one=True),
```

2021-07-16 07:25 UTC, simahawk requested changes
Quick update: rebase required, OCA PRs still pending, fix/imp to cherry pick from v13

2021-07-22 15:50 UTC, sebastienbeau commented
@simahawk I have cherry-pick the IMP here : https://github.com/shopinvader/odoo-shopinvader/pull/1028
Do you see other FIX/PR to pick ?

2021-07-23 06:11 UTC, simahawk commented
> @simahawk I have cherry-pick the IMP here : #1028
> Do you see other FIX/PR to pick ?

just check the log on v13 https://github.com/shopinvader/odoo-shopinvader/commits/13.0/shopinvader_sale_packaging

there are several commits missing before that one:

https://github.com/shopinvader/odoo-shopinvader/commit/3928aee96e9e48c344249679f08cb8f37740ca78
https://github.com/shopinvader/odoo-shopinvader/commit/479aae0292fae500b1f4ca2e142af495657bf8fe
https://github.com/shopinvader/odoo-shopinvader/commit/d0dc09e6a32a811e54573be94206b3ae2fdb3fc1
https://github.com/shopinvader/odoo-shopinvader/commit/c083aa62721d5079c5e7627757699c5e8a2d9ff7
https://github.com/shopinvader/odoo-shopinvader/commit/304f9baee18c017b0938c31e22c116d5aa759d21
https://github.com/shopinvader/odoo-shopinvader/commit/b586d64ea00e0fc1899fe4849a0c852a73b84845

2021-08-16 07:09 UTC, simahawk commented
@hparfr @PierrickBrun hello :)
Is anyone going further with this?

2021-08-26 13:12 UTC, hparfr commented
@sebastienbeau will you continue the cherry-pick :cherries:  ?

2021-09-06 12:18 UTC, simahawk commented
@sebastienbeau ping :)

2021-10-05 15:26 UTC, kevinkhao commented
I think we can continue over there https://github.com/shopinvader/odoo-shopinvader/pull/1131 because I do not see a clean way to keep working on this PR.

2021-10-06 06:44 UTC, closed without merging