[14.0] [MIG] shopinvader_invoice
shopinvader/odoo-shopinvader pull request #881
Opened 2021-02-10 14:34 UTC by david-popa

2021-02-10 14:39 UTC, acsonefho requested changes
Only remarks about compatibility between shopinvader versions.

2021-02-10 14:39 UTC, acsonefho commented on shopinvader_invoice/services/invoice.py
> +            "move_id": {"type": "integer"},
IMO: To keep compatibility between version and as the link between Odoo and Json values should stay abstract, I prefer to let this schema as origin and only edit the parser to match with this structure.

2021-02-10 14:39 UTC, acsonefho commented on shopinvader_invoice/services/invoice.py
> +                "type_label": self._get_selection_label(invoice, "move_type"),
So no change here too

2021-02-10 14:39 UTC, acsonefho commented on shopinvader_invoice/services/invoice.py
> +            "id:move_id",
Here you can let the `invoice_id`

2021-03-26 14:00 UTC, hparfr approved these changes

2021-03-26 14:00 UTC, hparfr commented
@acsonefho can you finish your review ?

2021-03-26 14:06 UTC, acsonefho approved these changes
Code LGTM!

2021-03-26 14:28 UTC, hparfr commented
/ocabot merge nobump

2021-03-26 14:39 UTC, merged