[MIG] shopinvader_customer_price_wishlist: Migration to 14.0
shopinvader/odoo-shopinvader pull request #901
Opened 2021-03-01 11:08 UTC by chafique-delli

2021-07-16 07:14 UTC, simahawk requested changes

2021-07-16 07:14 UTC, simahawk commented on oca_dependencies.txt
> -# See https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#oca_dependencies-txt
IDT think we need this as we use MQT=PIP here. You could trash the file.

2021-10-07 07:57 UTC, simahawk commented
@kevinkhao can you rebase? Should fix tests

2021-10-07 08:32 UTC, kevinkhao commented
renamed testcase here https://github.com/shopinvader/odoo-shopinvader/pull/1142

2021-10-08 06:18 UTC, simahawk commented
@kevinkhao #1142 is getting merged

2021-10-15 06:32 UTC, simahawk commented
@kevinkhao could you check the build?
```
2021-10-08 09:52:20,977 422 ERROR odoo odoo.addons.shopinvader_customer_price_wishlist.tests.test_wishlist_price: ERROR: WishlistCase.test_jsonify_custom_pricelist
Traceback (most recent call last):
  File "/__w/odoo-shopinvader/odoo-shopinvader/shopinvader_customer_price_wishlist/tests/test_wishlist_price.py", line 53, in test_jsonify_custom_pricelist
    self.discount_pricelist, self.backend._get_fiscal_position(self.partner)
  File "/__w/odoo-shopinvader/odoo-shopinvader/shopinvader_product_price_tax/models/shopinvader_variant.py", line 13, in _get_price
    qty=qty, pricelist=pricelist, fposition=fposition, company=company
  File "/__w/odoo-shopinvader/odoo-shopinvader/shopinvader/models/shopinvader_variant.py", line 242, in _get_price
    if pricelist and pricelist.discount_policy == "without_discount":
AttributeError: 'account.fiscal.position' object has no attribute 'discount_policy'
```

2021-10-15 13:59 UTC, kevinkhao commented
function signature changed with named arguments
I put the named arguments

2021-10-18 09:07 UTC, simahawk approved these changes

2021-10-21 07:00 UTC, simahawk commented
/ocabot merge nobump

2021-10-21 07:32 UTC, merged