[13.0][FIX] shopinvader: add backend into sell order view
shopinvader/odoo-shopinvader pull request #934
Opened 2021-03-26 16:44 UTC by david-popa

superseeds #879

2021-03-26 16:48 UTC, rousseldenis approved these changes

2021-03-26 17:11 UTC, hparfr requested changes

2021-03-26 17:11 UTC, hparfr commented on shopinvader/views/sale_view.xml
> +                <field name="shopinvader_backend_id" readonly="True"/>
can you add readonly in model instead ?

2021-04-20 10:55 UTC, HviorForgeFlow approved these changes

2023-04-29 23:20 UTC, closed without merging