[14.0][FIX] unique constraint on external_id
shopinvader/odoo-shopinvader pull request #956
Opened 2021-05-06 13:54 UTC by david-popa

Some of the tests were reusing the same external_id but there is a unique sql constraint in the shopinvader_locomotive module that allows only unique external_ids for a backend: https://github.com/shopinvader/odooshopinvader/blob/14.0/shopinvader_locomotive/models/locomotive_binding.py#L27

2021-07-16 07:36 UTC, simahawk requested changes

2021-07-16 07:36 UTC, simahawk commented on shopinvader_customer_multi_user/tests/common.py
> +    @staticmethod
I've done something similar here https://github.com/shopinvader/odoo-shopinvader/commit/b94138f8638ef277a2b95e4c2ceb18a17014ac29 (which should fix the same issue of this PR).

Maybe better to add this to the common utils mixin and call it `_get_random_ext_id`?

2021-10-08 09:27 UTC, lmignon commented
@david-popa Can you take into account the comment from Simone and fix the test so we can merge this PR and use the method into others tests?

2021-10-11 08:42 UTC, lmignon commented
superseded by #1071

2021-10-11 08:42 UTC, closed without merging