[MIG] shopinvader_customer_multi_user_wishlist: Migration to 14.0
shopinvader/odoo-shopinvader pull request #980
Opened 2021-05-25 09:27 UTC by simahawk

Depends on:
- [ ] #972

2021-07-15 10:32 UTC, simahawk commented
@ivantodorovich ping

2021-07-15 12:31 UTC, ivantodorovich requested changes
`"installable": True`

2021-07-15 14:06 UTC, ivantodorovich approved these changes

2021-07-16 06:24 UTC, simahawk commented
/ocabot merge nobump

2021-07-16 06:43 UTC, merged